project:
  type: book
  output-dir: _sites
  resources:
    - .nojekyll
    - slides/
    - images/

book:
  title: Social Networks
  subtitle: An Introduction
  author: Omar Lizardo and Isaac Jilbert
  date: 1/15/2023
  search:
    location: sidebar
    type: textbox
  page-navigation: true
  page-footer: "Copyright 2023, Omar Lizardo & Isaac Jilbert" 
  
  chapters:
    - index.qmd
    
    - part: "Introduction to Networks"
      chapters:
        - lesson-theory-what-are-networks.qmd
        - lesson-theory-what-are-social-networks.qmd
        - lesson-theory-ties-bound.qmd
        - lesson-theory-tie-strength.qmd
        - lesson-theory-multiplex.qmd
        
    - part: "Networks and Graphs"
      chapters:
        - lesson-graphs-intro.qmd
        - lesson-graphs-ties.qmd
        - lesson-graphs-dyads-triads.qmd
        - lesson-graphs-metrics.qmd
        - lesson-graphs-directed.qmd
        - lesson-graphs-paths.qmd
        - lesson-graphs-connectivity.qmd
        - lesson-graphs-trees.qmd

    - part: "Networks and Matrices"
      chapters:
        - lesson-matrix-intro.qmd
        - lesson-matrix-network.qmd
        - lesson-matrix-operations.qmd
        - lesson-matrix-multiplication.qmd

    - part: "Centrality and Status"
      chapters:
        - lesson-sna-degree-centrality.qmd
        - lesson-sna-closeness.qmd
        - lesson-sna-betweenness.qmd
        - lesson-sna-bigthree.qmd
        - lesson-sna-eigenvector.qmd
        - lesson-sna-status.qmd
        - lesson-sna-hubs-and-authorities.qmd

    - part: "Two-Mode & Ego Networks"
      chapters:
        - lesson-sna-affiliation-networks.qmd
        - lesson-sna-ego-networks.qmd
        - lesson-sna-ego-collect.qmd
        - lesson-theory-ego-homo.qmd
        - lesson-theory-network-cognition.qmd

    - part: "Subgroups and Blocks"
      chapters:
        - lesson-sna-groups-cliques.qmd
        - lesson-sna-groups-cohesive.qmd
        - lesson-theory-struct-equiv.qmd
        - lesson-positions-advanced-equiv.qmd
        - lesson-sna-local-similarity.qmd
        - lesson-sna-blockmodeling.qmd

    - part: "Network Theory: Ties and Circles"
      chapters:
        - lesson-theory-dunbar.qmd
        - lesson-theory-swt.qmd
        - lesson-theory-sht.qmd
        - lesson-theory-smt.qmd

    - part: "Network Theory: Balance and Hierarchy"
      chapters:        
        - lesson-theory-balance-dyadic.qmd
        - lesson-theory-balance-triadic.qmd
        - lesson-theory-balance-struct.qmd
        - lesson-theory-valenced-interactions.qmd
        - lesson-theory-hierarchies.qmd

    - part: "Network Theory: Dynamics and Diffusion"
      chapters: 
        - lesson-theory-diffusion.qmd
        - lesson-theory-small-world.qmd

    - references.qmd



bibliography: networks.bib

format:
  html:
    css: styles.css
    page-layout: full
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]    
    toc: true
    linkcolor: "#ff7e26"
    citation-location: margin
    reference-location: margin
    

execute:
  echo: false
  warning: false
  message: false
  freeze: auto

editor: source
