project:
  type: book
  output-dir: _sites
  resources:
    - .nojekyll
  render:
    - "*.qmd"
    - "!*_*.qmd_"
    - "!*-5562048.qmd"
  post-render:
    - "powershell -ExecutionPolicy Bypass -File render_homeworks.ps1"

book:
  title: Social Networks
  subtitle: An Introduction
  author: Omar Lizardo and Isaac Jilbert
  date: 1/15/2023
  search:
    location: sidebar
    type: textbox

  page-navigation: true
  page-footer: "Copyright 2023, Omar Lizardo & Isaac Jilbert" 
  chapters:
    - index.qmd
    - part: "Introduction to Networks"
      chapters:
      - lesson-theory-what-are-networks.qmd
      - lesson-theory-what-are-social-networks.qmd
      - lesson-theory-ties-bound.qmd
      - lesson-theory-tie-strength.qmd
    - part: "Graph Theory: The Basics"
      chapters:
      - lesson-graphs-intro.qmd
      - lesson-graphs-directed.qmd
      - lesson-graphs-subgraphs.qmd
      - lesson-graphs-ties.qmd
      - lesson-graphs-metrics.qmd
      - lesson-graphs-neighborhoods.qmd
      - lesson-graphs-degree.qmd
      - lesson-graphs-degree-metrics.qmd
      - lesson-graphs-paths.qmd
      - lesson-graphs-directed-paths.qmd
      - lesson-graphs-directed-metrics.qmd
      - lesson-graphs-connectivity.qmd
      - lesson-graphs-trees.qmd
      - lesson-graphs-other-graphs.qmd
    - part: "Matrices: The Basics"
      chapters:
      - lesson-matrix-intro.qmd
      - lesson-matrix-adjacency.qmd
      - lesson-matrix-row-column-sums.qmd
      - lesson-matrix-operations.qmd
      - lesson-matrix-multiplication.qmd
      - lesson-matrix-special-matrices.qmd
      - lesson-matrix-operations-adv.qmd
    - part: "Motifs"
      chapters:
      - lesson-graphs-dyads-and-triads.qmd
    - part: "Centrality"
      chapters:
      - lesson-sna-degree-centrality.qmd
      - lesson-sna-closeness.qmd
      - lesson-sna-betweenness.qmd
      - lesson-sna-bigthree.qmd
      - lesson-sna-eigenvector.qmd
      - lesson-sna-status.qmd
      - lesson-sna-hubs-and-authorities.qmd
    - part: "Two-Mode Networks"
      chapters:
      - lesson-sna-affiliation-networks.qmd
    - part: "Ego Networks"
      chapters:
      - lesson-sna-ego-networks.qmd
      - lesson-sna-ego-collect.qmd
      - lesson-theory-ego-homo.qmd
    - part: "Subgroups and Blocks"
      chapters:
      - lesson-sna-groups-cliques.qmd
      - lesson-sna-groups-cohesive.qmd
      - lesson-positions-struct-equiv.qmd
      - lesson-sna-local-similarity.qmd
      - lesson-sna-blockmodeling.qmd
    - part: "Network Theory"
      chapters:
      - lesson-theory-dunbar.qmd
      - lesson-theory-swt.qmd
      - lesson-theory-sht.qmd
      - lesson-theory-smt.qmd
      - lesson-theory-dyadic-balance.qmd
      - lesson-theory-triadic-balance.qmd
      - lesson-theory-structural-balance.qmd
      - lesson-theory-valenced-interactions.qmd
      - lesson-theory-hierarchies.qmd
      - lesson-theory-diffusion.qmd
      - lesson-theory-small-world.qmd
    - part: "Exercises"
      chapters:
      - homework1.qmd
      - homework2.qmd
      - homework3.qmd
      - homework4.qmd
      - homework5.qmd
      - homework6.qmd
      - homework7.qmd
      - homework8.qmd
      - homework9.qmd

bibliography: networks.bib

format:
  revealjs:
    css: ucla-theme.css
  html:
    css: styles.css
    page-layout: full
    theme:
      light: flatly
      dark: darkly    
    toc: true
    linkcolor: "#ff7e26"
    

execute:
  echo: false
  warning: false
  message: false
  freeze: auto

editor: source

