import os
import re

def get_active_chapters():
    chapters = []
    if not os.path.exists('_quarto.yml'):
        print("Warning: _quarto.yml not found. Checking all .qmd files in directory.")
        return [f for f in os.listdir('.') if f.endswith('.qmd')]
        
    with open('_quarto.yml', 'r', encoding='utf-8') as f:
        content = f.read()
        # Find all .qmd files in _quarto.yml
        matches = re.findall(r'-\s+([a-zA-Z0-9_-]+\.qmd)', content)
        for m in matches:
            if m not in chapters:
                chapters.append(m)
    return chapters

def check_references():
    chapters = get_active_chapters()
    print(f"Checking {len(chapters)} active chapters listed in _quarto.yml...")
    
    # Check for missing files first
    missing_files = [f for f in chapters if not os.path.exists(f)]
    if missing_files:
        print("\n[WARNING] The following chapter files listed in _quarto.yml do not exist:")
        for f in missing_files:
            print(f"  - {f}")
            
    # Remove non-existent files from chapters to avoid file read errors
    chapters = [f for f in chapters if os.path.exists(f)]
    
    defined = {}  # label -> file where defined
    references = []  # list of tuples: (ref_label, file_where_referenced, line_num, full_line_text)
    
    inline_label_re = re.compile(r'\{#(fig|tbl|sec|eq|thm|lem|cor|prp|cnj|def|exm|rem)-([a-zA-Z0-9_-]+)')
    chunk_label_re = re.compile(r'#\|\s*label:\s*"?((?:fig|tbl|sec|eq|thm|lem|cor|prp|cnj|def|exm|rem)-[a-zA-Z0-9_-]+)"?')
    ref_re = re.compile(r'@(fig|tbl|sec|eq|thm|lem|cor|prp|cnj|def|exm|rem)-([a-zA-Z0-9_-]+)')
    
    for f in chapters:
        try:
            with open(f, 'r', encoding='utf-8') as file:
                for line_idx, line in enumerate(file, 1):
                    # Find inline label definitions
                    for match in inline_label_re.finditer(line):
                        label = f"{match.group(1)}-{match.group(2)}"
                        defined[label] = f
                        
                    # Find chunk label definitions
                    for match in chunk_label_re.finditer(line):
                        label = match.group(1)
                        defined[label] = f
                        
                    # Find references
                    for match in ref_re.finditer(line):
                        ref = f"{match.group(1)}-{match.group(2)}"
                        references.append((ref, f, line_idx, line.strip()))
        except Exception as e:
            print(f"Error reading {f}: {e}")
            
    # Resolve references
    broken = []
    valid_count = 0
    for ref, ref_file, line_num, line_text in references:
        if ref in defined:
            valid_count += 1
            continue
            
        # Check if it has a dynamic suffix (e.g. -1, -2 for subfigures/plots generated by knitr)
        if re.search(r'-\d+$', ref):
            base_ref = ref.rsplit('-', 1)[0]
            if base_ref in defined:
                valid_count += 1
                continue
                
        broken.append((ref, ref_file, line_num, line_text))
        
    print(f"\nFound {len(defined)} defined labels and {len(references)} references.")
    print(f"Successfully resolved {valid_count} references.")
    
    if broken:
        print(f"\n[ERROR] Found {len(broken)} potentially broken references:")
        # Sort by file and line number
        broken.sort(key=lambda x: (x[1], x[2]))
        current_file = ""
        for ref, ref_file, line_num, line_text in broken:
            if ref_file != current_file:
                print(f"\nFile: {ref_file}")
                current_file = ref_file
            print(f"  Line {line_num:3d}: @{ref}")
            print(f"            Text: {line_text}")
    else:
        print("\n[SUCCESS] No broken references found in active chapters!")
        
    # Extra credit: unused defined labels
    referenced_labels = set(r[0] for r in references)
    unused = []
    for label, def_file in defined.items():
        if label not in referenced_labels:
            # Check if this is a base label for which a sub-figure was referenced (e.g., base-1 is referenced but base itself is not)
            is_sub_referenced = False
            for r in referenced_labels:
                if r.startswith(label + "-"):
                    is_sub_referenced = True
                    break
            if not is_sub_referenced:
                unused.append((label, def_file))
                
    if unused:
        print(f"\n[INFO] Found {len(unused)} defined labels that are never referenced:")
        unused.sort(key=lambda x: (x[1], x[0]))
        current_file = ""
        for label, def_file in unused:
            if def_file != current_file:
                print(f"  File: {def_file}")
                current_file = def_file
            print(f"    - {label}")

if __name__ == '__main__':
    check_references()
