# Ego-Network Matrix Notation
In what follows we will abide by the following notational conventions:

- We will refer to the **ego node** using the subscript $i$
- We will refer to the **alter nodes** using the subscript $j$
- When referring to **ego-alter ties** we will use the term $E_{ij}$, which can be read as "the edge that goes from ego ($i$) to alter node $j$."
- When distinguishing between two different **alter nodes** we will use the subscript $j$ and $j'$.^[This last is read as "j prime."] 
- When referring to **alter-alter ties** we will use the term $E_{jj'}$, which can be read as "the edge that goes from one alter ($j$) to another alter node ($j'$)." 
# Ego Network Metrics


 Thus, ego network size is given by:

\begin{equation}
  S = E_{ij}
\end{equation}

This equation says that we compute the size of the ego network by summing over the links that have ego ($i$) as one of their endpoints and which have ego's neighbors as the other endpoint node. One way of saying this is that those nodes ($j$) have to be members of the set of ego's neighbors ($N(i)$).^[The mathematical symbol for set membership is $\in$.]


### Relative and Expected Rates

When it comes to homophily, there are two ways of measuring the propensity of an actor to associate with those who are the "same" as they are. **Relative rates** are when actors demonstrate preferences for some groups of actors relative to other groups of actors. Thus, if Ashley has 10 friends in college, seven of which are female and three of which are male, then Ashley seems to prefer having female friends relative to having male friends.

However, what if Ashley goes to a college where there are 700 female students and 300 male students? Would we still think of Ashley as having a preference for female friends? This is the logical behind expected rates. **Expected rates** are when researchers try to understand with what likelihood an actor would choose a friend at random and then compare that to the observed rate. In this case, at random there is a 70% chance Ashley would choose a female friend and a 30% chance a male friend would be made. Thus, Ashley does not demonstrate a preference for female friends, but actually seems to make friends regardless of gender. If we used a relative rate, we would conclude Ashley prefers female college friends, while under an expected rate, Ashley seems to not care for gender in her friendship decisions.

While it might seem to make more sense to rely on expected rates in research, it is incredibly hard to know what the underlying population of potential associates actually looks like. At the national population level we often have census statistics that could help us know that, if you made a friend at random somewhere in the US, what the odds they would be between 54-65 and female would be. That might not be useful for the specific research question however as people make friends in their communities- schools, clubs, neighborhoods. If you are interested in the case of racial friendship at the neighborhood level, you might not know everyone in the neighborhood. Comparing the observed homophily in respondents' ego networks might be the best one can do [@ignatow13]. Understanding what tools the researcher can access to best examine their question is of critical importance in attainable, as opposed to perfect, research.