# Tie Strength

## The Content of Social Relations
In everyday life, we tend to distinguish different types of social relations by their **content**. For instance, you distinguish between the relationships you have with your *parents* from those you have with your *friends*. Within your friendship group, you distinguish between different *types of friends*. For instance, you may say "that's my *work friend* or "that's my *best friend*. There are some relationships that are one of a kind (or exclusive, in the sense that it wouldn't be appropriate to have multiple of them at the same time) like the one you have with your *significant other*. 

Sometimes, there are rules against mixing relationship contents. Although it has become more common of late, in some cultures it is still weird for your *parent* to also be your *best friend*. Or for your *boss* to also be your *confidant*. Some relationships that mix contents may even acquire a new content designation as when you have a *friend* who is also a *sexual partner*, but not necessarily your *significant other*. Of course, these relationship content examples draw from common knowledge in the Euro-American west, but anthropologists, historians, and area scholars have cataloged myriad of relationship contents that have been developed across different historical eras, nations, and geographical regions. Most of them, like the *patronage* relation in early modern Europe (and the related *patron* relation in some parts of Latin America), have no real counterpart in the United States today. 

Sorting relations by the *activities* you do with others is another way of distinguishing social ties based on content in the contemporary era. Thus, you can have your *workout buddies*, or your *pick up basketball crew* or your *clubbing posse*. You can also have friends that you only see at *chess club* or your favorite *reading group*, or people you only know via *online gaming*.  

## The Form of Social Relations
Network analysis in the social sciences is distinctive because it breaks with commonsense practice in differentiating social relations not based on their content, but rather based on their **form** [@burt82, 22]. For instance, one aspect of the form of social relationships is the **tie strength** or the **intensity** of the relationship between two people. As we will see, tie strength has many components, but the point is that the formal characteristics of relations *cut across* different types of contents. Thus, we can have friends that we don't really feel than intensely about, which is different from our *close friends* that we do feel intensely about. 

Closeness, as a formal feature of social ties, can also show up in kin relations (my *close relative*) or even specialized relations (my *closest friend at work*). Other aspects of intensity, like frequency of interaction cuts across relationship types. Thus, you can have people who you don't consider "friends" in terms of content, but with who you have a very intense relation in terms of form, like co-workers that you interact with and see everyday, more than you may see your family members! 

Another formal aspect of social relations, based on activities, is the number of *shared activities* you have with others. This is a version of intensity, since clearly someone you share *multiple activities* with (a person who is your golf buddy, and your drinking buddy, and your workout buddy) is more important than a person you share no or only a single activity with. This formal aspect of social ties was discussed in @sec-affil.

## Defining Tie Strength
Tie strength is arguably the most important formal property of social ties. At least, it is the one that has been most argued about, theorized, and researched in sociological network analysis [@marsden_campbell84]. To give you a sense of how important tie strength is, the sociologist [Mark Granovetter](https://en.wikipedia.org/wiki/Mark_Granovetter) wrote and article in 1973 entitled "The Strength of Weak Ties," which has become one of the most highly referenced articles in the history of social science [@granovetter73]. 

Clearly tie strength is a *big deal*. But what is it exactly?

Well begin with the intuition that, if you were to scan the various ties in your **ego network**, not all would be of the same intensity. You will feel very close to some people, want to hang out with them often, and be willing to support them (financially, emotionally, helping them move). Other people in your social network, you may like just fine, but you just don't feel that close to them and are not willing to given them the shirt off your back. So intuitively, the first kinds of ties are **strong ties** and the second kind of ties are **weak ties**. Everyone's local social network is a mixture of strong and weak ties (and everything in between). 

So clearly, while we can get an intuitive idea of what a strong and a weak tie is, we need to get more specific. It is clear that from the above description that tie strength is not a *single* property of ties. Instead, it is a *cluster* of such properties that somehow hang together. So it is important to enumerate the core components of tie strength, because theoretically they can be measured separately. Besides, it is also important to keep those properties that are unique to tie strength distinct from other tie properties. 

There has been a tendency in the literature to *confuse* the concept of tie strength for what are in fact other tie properties that just happen to be typically correlated with it like similarities and the varieties of structural embeddedness discussed later). So there is difference between saying "typically when people share a lot of similarities their tie is *likely* to be strong" and saying "similar ties *are* strong ties."

So what are the subproperties that together make up a strong tie? To begin we can consult the definition of **tie strength** Granovetter provided in his classic paper. According to Granovetter, tie strength is "...a (probably linear) combination of the amount of time, the emotional intensity, the intimacy (mutual confiding) and the reciprocal services which characterize the tie" [@granovetter73,  1361].

So here Granovetter mentions the four core components that would later on be canonized by the sociologists Peter Marsden and Karen Campbell as the core **indicators of tie strength** [@marsden_campbell84]. 

### Duration and Frequency
To begin, strong ties are the ones that take up most of your time and that have lasted the longest. That is **frequency of interaction** and **tie duration** are two core subproperties that strong ties have. *Think of your the friends that you hang out with often and that you've known for a long time; those ties are strong*. 

### Support and Reciprocal Services
The other things Granovetter mentions are number of behaviors that people who have strong ties do with respect to each other. First, you can *confide* in your strong ties (tell them secrets or sensitive info about you); second people who share a strong tie *do things* for one another ("reciprocal services"). In the social networks literature these set of behaviors are known as **social support**. So you can provide support to your strong ties by listening to guarding their secrets and listening to their problems, or helping them study, or lending them twenty bucks. *So the ties that feature a heavy (two way!) reciprocal flow of services and mutual confiding are strong*.  

### Subjective Closeness
Last, and very much not least, you wouldn't be hanging out with people or keeping a tie alive for a long time, or helping them with their trials and tribulations unless you didn't have an *emotional attachment* to those people! So strong ties are those that feature (once again mutual) feelings of **subjective closeness** and that's exactly how you would describe them to a sociologist if they came asking. *Strong ties are those people in your network you feel closest to*. 

So there you have it. Strong ties are those connections you have that have lasted the longest, you interact with most frequently, feature mutual support and confiding, and you feel closest to. If a tie has all these components then it is strong for sure. If it lacks all these components, there is no question that it is weak. 

## The Tie Strength Continuum 

However, the question of whether a tie is strong or weak is not a "yes/no," or "black/white" thing. The reason for this is that while all four indicators or tie strength are *correlated* they are not deterministically linked to one another. Some ties can be high on some indicators and low in others. This is why rather than a binary there is a **tie strength continuum**. Some ties are just in-between because they contain a mixture of strong and weak components. 

For instance, there people at work you see every day but are not that subjectively close to. By the same token, there may be a friend from high school that lives in a faraway place you don't hang out with or communicate very often, but you feel very close to. These ties are "in between" strong and weak. 

Ties between parents and children also have features of both strong and weak ties. For instance, parents tend to provide their children with a lot of support (usually of the emotional and financial kind), but parents seldom (lest we get a case of the TMIs!) share their deepest sexual secrets or marital difficulties with their children (or vice versa). **Kin ties** in general (including that between siblings) tend to combine features of strong and weak ties.^[In sociology and anthropology, **kin ties** is the technical term for ties between family members. Ties to people outside the family (friends, acquaintances) are referred to as **non-kin ties**.] You usually feel subjective close to your brother or sister, but that doesn't mean you hang out with them all the time. 

Another example of a "mixed" strong/weak tie is the "love at first sight" phenomenon. Here we have a tie with very little duration (they just met!) but featuring a strong emotional feeling of closeness. Maybe the reason people find love at first sight strange or counter-intuitive is because it combines strong and weak tie properties. 

Examples could be expanded indefinitely, but the take-away point is that *most ties in social networks are not super strong or super weak, but are somewhere in between, featuring components of both strong and weak ties*. 


