# Balance {#sec-balance}

## Dyadic Balance

In @sec-ties, we distinguished between two types of ties between people. On the one hand there are relations like spend time with, going to the same school, belonging to the same club, buying coffee from the same shop, being a member of the same gender, ethnic, sexual, national, category. These are relationships that imply some kind of similarity, co-membership between people. 

We referred to these as **symmetric ties** because they do not imply any directionality. Thus, if $R$ is a relation implied by a symmetric tie, and if $aRb$ (reads "a is tied to b via symmetric relation R") then, by definition $bRa$. So if $a$ has the same gender identity as $b$, then $b$ has the same gender identity as $a$, if $a$ is the same class as $b$, then $b$ is the same class as $a$, and so on for all symmetric ties and any pair of people $a$ and $b$. 

As we also saw, the other way people can be linked in social networks is via **asymmetric ties**. These are relationships that have an implied *directionality* (they start in one person and are sent to another) and have the *potential* to be either **reciprocated** or not reciprocated. For instance, helping, giving advice, liking, loving, hating, sending a text, retweeting, are all asymmetric ties in this sense.

One person can help another person, but the person may no help them back. One person can retweet another person's tweet, but that person could or could not retweet the first person's tweet, more painfully, a person can love another, and the other person could not love them back, and so forth. 

Typically, we are tied to other people via a multiplicity of ties. That is, we are tied to others via what anthropologists called **multiplex ties**. That is, a person we like, may also be a person we hang out with, which may also be a person that shares our ethnic identity (what in @sec-egonets we called **homophily**), which may also be a person we go to the movies with, and so on. 

The theory of **dyadic balance** was developed by the social psychologist [Fritz Heider](https://en.wikipedia.org/wiki/Fritz_Heider) to understand how all these different ties linking us to other people go together [@heider46]. Heider's dyadic balance theory had two simple ideas. First, he proposed that symmetric ties based on similarities tend to generate or give rise to positive asymmetric ties. For instance, if you spend a lot of time together with another person you will end up liking that person. 

If $S$ is the "spend time together" symmetric tie, and $L$ is the "liking" asymmetric tie, Heider proposed that $aSb \rightarrow aLb$, which can be read as "people who spend time together end up liking one another." Of course, once this first step is complete, the two ties can become embedded in a **positive feedback loop**, so that they mutually reinforce one another, since we like to spend time together with the people we like: Thus $aLb \rightarrow aSb$. More generally, Heider proposed that symmetric ties of similarity, co-membership and so forth, give rise to positive asymmetric ties such as liking, admiring, helping, giving advice to, and so forth. 

This also means that over time, people will accumulate many types of symmetric and asymmetric ties. For example, two people can begin as co-workers (a symmetric tie), which leads to having lunch together (another symmetric tie), which leads to mutual liking (a pair of asymmetric ties), which leads to hanging out outside work (another symmetric tie), which leads to one person confiding their secrets on another (a one way asymmetric tie), and so forth. This is the reason why most people are linked to one another via a multiplicity of ties, a phenomenon that anthropologists refer to as **multiplex ties** (also called "multistranded" ties). So even if a tie *begins* its life as a single-stranded uniplex tie (like working together), it will tend, over time, to become a multiplex tie. 

In this way, symmetric ties based on similarity can be thought of as asymmetric *tie formation mechanisms*. That is, similarities (of whatever type) breed liking, which breed friendship, social support, texting, advice giving, and many other kinds of ties v for the same two people. For the type of liking that emerges when people spend time in the same place (like taking a social networks class), social scientists have a special name: The **principle of propinquity**. According to this theory, you learn to like the people you end up sharing space with [@newcomb56, p. 580].

The second key idea in Heider's dyadic balance theory is that, once we become connected to other people via multiplex ties, we try to keep the connection between symmetric ties based on similarities and positive asymmetric ties. That is, we try to like the people that we are similar to. This means that we try to *avoid* situations in which we are connected to others by a symmetric tie, while at the same time being connected to them via a *negative* asymmetric link. Think, for instance, how hard an uncomfortable it is to have co-workers you dislike, or people who you think are similar to you (e.g., have the same racial or ethnic identity) that you find unpleasant. 

So if $D$ is an asymmetric dislike tie, then via the principle of dyadic balance, the situation $aSb \land aDb$ (which reads "$a$ spends time with $b$ *and* $a$ dislikes $b$") is *unbalanced* because $D$ is a negative asymmetric tie. In this, arrangement $a$ is spending time with someone, $b$, whom they dislike (as when we are spend time together with a despised co-worker). This situation creates **cognitive inconsistency** and an unpleasant affective state of **tension**. Heider predicts that in order to resolve the imbalance we either break the $S$ tie (in our example find a new place to work!) or if the $S$ tie can't be broken and you have to spend time with the disliked person, you can *change the $D$ tie to an $L$ tie*. That is, we learn to start liking the people we are spending time with. The same goes for any other kind of similarity based on co-membership or belonging to the same social category. 


## References {.unnumbered}