---
title: "A Tufte Handout Example"
runningheader: "Tufte Handout with R Markdown" # only for pdf output
subtitle: "An implementation in R Markdown" # only for html output
author: "JJ Allaire and Yihui Xie"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
link-citations: yes
---

# Homework Schedule
|Assignment | Due Date |
|:--------- |:--------:|
| Homework 1 | Due on Week 3 (Friday @ 5p) |
| Homework 2 | Due on Week 4 (Friday @ 5p) |
| Homework 3 | Due on Week 6 (Friday @ 5p) |
| Homework 4 | Due on Week 8 (Friday @ 5p) |
| Homework 5 | Due on Week 10 (Friday @ 5p) |

# Lecture Schedule

**All readings indicated are from the online textbook to be found here:**:  [http://olizardo.bol.ucla.edu/classes/soc-111/textbook/_book/](http://olizardo.bol.ucla.edu/classes/soc-111/textbook/_book/)

## Week 1 

*Monday, January 4, 2021*

- Introduction: What are Networks?^[*Reading: Chapter 1, Introduction.*]
  - Types of Networks  
  - Social v. Non-Social Networks  
  - Network Science  
  - Social Network Analysis  
  - Social Network Theory  
  - Social Network Measurement  

*Friday, January 8, 2021*  

- The Nature and Types of Social Ties
  - Types of Connectivity
  - Symmetric Ties
  - Asymmetric Ties
  - Anti-Symmetric Ties
  - Multiplex Ties
  - Tie Strength 

## Week 2

*Monday, January 11, 2021*  

- Graph Theory
  - Edges and Nodes
  - Node Neighborhoods
  - Graphs and Subgraphs
  - Graph Metrics
    - Basic Graph Metrics
    - Graph Maximum Size
    - Graph Density
  - *Reading Chapter 2, Graph Theory, sections 2.1 through 2.3 and 2.7)*

*Friday, January 15, 2021*

- Representing Social Networks as Graphs
  - Types of Graphs
    - Undirected Graphs
    - Directed Graphs
    - Tree Graphs
    - Multigraphs
    - Weighted Graphs
  - Indirect Connectivity
    - Paths
    - Shortest Paths
    - Cycles
  - *Reading Chapter 3, Ties and Graphs, sections 4.1 through 4.6*

## Week 3
*Monday, January 18, 2021*

- **No Lecture: Martin Luther King, Jr. holiday**

*Friday, January 22, 2021*

- Representing Social Networks using Matrices 
  - Types of Social Network Matrices
  - Matrix Operations 
  - Computing Network Metrics from matrices
- *Reading Chapter 5, Matrices, sections 5.1 through 5.7*

## Week 4
*Monday, January 25, 2021*

- Ego Networks: Theory  
  - Dunbar's Ego Network Layers  
  - Blau's Macrostructural Theory  
  - Feld's Focus Theory  
  - Marsden's Ego Network Size Theory  

*Friday, January 29, 2021*

- Ego Networks: Metrics
  - Size
  - Homogeneity
  - Diversity
  - Clustering
- *Reading Chapter 7, Ego Nets*

## Week 5

*Monday, February 1, 2021*

- Basic Centrality Notions in Social Networks
  - Degree Centrality
  - Closeness Centrality
  - Betweenness Centrality
  - Eigenvector Centrality
- *Reading Chapter 6, Centrality*

*Friday, February 5, 2021*

- **No Lecture: Scheduled Midterm Exam**  
- (Open window from 7a-7p Pacific Standard Time)  
  - *Time: Limit 100 minutes*

## Week 6

*Monday, February 8, 2021*

- Cliques, Subgroups, and Communities
  - Groups in Social Networks
  - Cliques
  - Graph Connectivity
  - Cutsets
  - Menger's Theorem

*Friday, February 12, 2021*

- Triadic Processes in Networks
  - Balance Theory
  - Simmelian Tie Theory
  - Transivity in Social Networks
  
## Week 7

*Monday, February 15, 2021*

- **No Lecture: President's day holiday**

*Friday, February 19, 2021*

- Social Networks and Status Attainment
  - Social Networks and Social Capital
  - Strength of Weak Ties Theory
  - Structural Hole Theory
  - The Diversity/Bandwith Tradeoff

## Week 8
*Monday, February 22, 2021*

- Status, Hierarchy, and Valenced Interactions
  - Status Theory
  - Karma Theory
  - Solidarity Theory
  - Dominance Hierarchies
  - Negative Reciprocity


*Friday, February 26, 2021*

- Two Mode Networks
  - The Affiliation Matrix
  - The Comembership Matrix
  - The Group Overlap Matrix
  - Two Mode Network Metrics
- *Reading Chapter 8, Affiliation Nets*

## Week 9
*Monday, March 1, 2021*

- Small World Networks
  
*Friday, March 5, 2021*

- Roles and Positions in Networks
  - Structural Equivalence
  - Regular Equivalence

## Week 10

*Monday, March 8, 2021*

- The Diffusion of Innovations 
  - The S-Curve
  - Mechanisms of Diffusion

*Friday, March 12, 2021*

- The (Social) Psychology of Networks
  - Kadushin's Two-Function Theory
  - Cognitive Social Structures
  - Social Networks and Self-Monitoring
  - Personality and Social Networks

## Final Exam
Monday, March 15

- (Open window from 7a-7p Pacific Standard Time)
  - *Time: Limit 100 minutes*
