---
title: "What is a Social Tie?"
date: "`r Sys.Date()`"
output:
  bookdown::tufte_html2: default
bibliography: networks.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tint)
# invalidate cache when the package version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'), echo = FALSE, message=FALSE, warning=FALSE)
options(htmltools.dir.version = FALSE)
```

`r newthought('You may think that the idea of a social tie is a simple one.')` After all, what is more basic that being connected to other people? However, in social network analysis things are a little more complicated than that. The main issue is that both in natural language and in social scientific work, the idea of a social tie is **polysemous** this is a fancy word (taken from linguistics) that means that the term "social tie" can mean different things. For instance, we can be linked to other people because we share a deep a long-lasting friendship. In the same way, we can be linked to other people only because we share a very fleeting relationship; like the person who owns your favorite bakery and from which you buy delicious confections from. Both of these are a kind of "social tie" you have with others, but they are very different.

For social network analysts who are interested in collecting data, things get a bit more involved. The main question they are interested in is: What sort of information do I need to gather to say two people are connected? Some early network analysis work in anthropology used **observation**. That is an anthropologist simply observed people, and if they saw them talking, dancing, hugging, or eating together, they concluded that a social tie existed between these people. In the same way, sociologists in the 1970s decided that they could determine the social ties that people had by having them fill out long **questionnaires** (subsequently called **network surveys**). For instance, we could ask people to list the top 5, 10, or 20 contacts from whom they obtained various services, or they went for advice.

In the same way, sociologists of education studying kids in classrooms decided that they could just ask students in every class to provide an assessment of each of the whole **roster** other people in the class. You could ask Jill if they "liked" or "hung out with" Fernando, Nidia, Rohan, or Jamal. You could also even ask whether people had "negative" social ties with others (e.g., disliked them, or spread gossip about them). Today, there are even more ways of trying to figure out whether people are connected. For instance, we could check out your **social media** accounts and see if you liked someone's post or retweeted their tweet. We could check your **cell phone logs** and see you texted last week. We could download **email records** in a corporation and see who your top email contacts are, and so forth. These newfangled ways of collecting data or social ties associated with the advent of "big data" and "computational social science" [@borgatti09]. It seems like the options are endless!

Both the natural polysemy of the notion of social tie, and the recent efflorescence of different ways of determining whether such ties exist in the real world has led network analysts to rethink their approach to defining the idea of social ties [@kitts20]. The basic idea is that there are multiple ways of thinking about the idea of a social tie and that the job now is to come up with useful taxonomies (e.g., classifications) of these different ways so that we can group them into useful clumps.

The one thing that everyone seems to agree on, however, is that whatever they are **social ties** are the fundamental units of social networks. Like pieces of a jigsaw puzzle, social ties are the *building blocks* of larger network structures, and ultimately of society as whole. The basic idea is that social ties tend to bunch into definable clumps by attaching themselves to one another with people as the intermediaries. For instance, if you have a friend and you introduce them to another one of your friends, the two previously separate social ties between you and your two friends have now **concatenated** (joined together) into a larger structure (called a **connected triad** as we will see later).

# The Properties of Social Ties

To make sense of the booming buzzing confusion surrounding the concept of social tie, I propose an approach based on enumerating the core **properties** that social network analysts have proposed all social ties have. You will see that a lot of **network theories** are actually proposals about systematic linkages or correlations between the main tie properties. 

So what are the main properties of social ties? We will distinguish four broad classes: 

1. Properties associated with **tie strength**, which has to do with the intensity of feelings and sentiments, frequency of interaction, length of acquaintanceship, and patterns of social support between the people involved in the tie. 
1. Properties having to do with **similarities** in the properties, behaviors, situations, or beliefs of the people involved in the tie.
1. Properties associated with various forms of **reciprocity** and **non-reciprocity** regarding the various actions people can direct toward one another (communication, exchanges, advice, acknowledgement, sentiments) in the context of the relationship. 
1. Properties associated with the **structural embeddedness** of the tie which is linked to the surrounding social environment of other people connected to both actors in the tie.
1. Properties linked to the **temporal signature** of the interactions, exchanges, and communications between the two actors in the tie. 

## Tie Strength 

`r newthought('Tie strength is arguably the most important property of social ties')`. At least, it is the one that has been most argued about, theorized, and researched in sociological network analysis [@marsden84]. To give you a sense of how important tie strength is, the sociologist [Mark Granovetter](https://en.wikipedia.org/wiki/Mark_Granovetter) wrote and article in 1973 entitled "The Strength of Weak Ties," which has become one of the most highly referenced articles in the history of social science [@granovetter73]. 

Clearly tie strength is a *big deal*. But what is it exactly?

## Defining Tie Strength

Well begin with the intuition that, if you were to scan the various ties in your **ego network**, not all would be of the same intensity. You will feel very close to some people, want to hang out with them often, and be willing to support them (financially, emotionally, helping them move). Other people in your social network, you may like just fine, but you just don't feel that close to them and are not willing to given them the shirt off your back. So intuitively, the first kinds of ties are **strong ties** and the second kind of ties are **weak ties**. Everyone's local social network is a mixture of strong and weak ties (and everything in between). 

So clearly, while we can get an intuitive idea of what a strong and a weak tie is, we need to get more specific. It is clear that from the above description that tie strength is not a *single* property of ties. Instead, it is a *cluster* of such properties that somehow hang together. So it is important to enumerate the core components of tie strength, because theoretically they can be measured separately. Besides, it is also important to keep those properties that are unique to tie strength distinct from other tie properties. 

There has been a tendency in the literature to *confuse* the concept of tie strength for what are in fact other tie properties that just happen to be typically correlated with it like similarities and the varieties of structural embeddedness discussed later). So there is difference between saying "typically when people share a lot of similarities their tie is *likely* to be strong" and saying "similar ties *are* strong ties."

So what are the subproperties that together make up a strong tie? To begin we can consult the definition of **tie strength** Granovetter provided in his classic paper. According to Granovetter, tie strength is "...a (probably linear) combination of the amount of time, the emotional intensity, the intimacy (mutual confiding) and the reciprocal services which characterize the tie" [@granovetter73,  1361].

So here Granovetter mentions the four core components that would later on be canonized by the sociologists Peter Marsden and Karen Campbell as the core **indicators of tie strength** [@marsden84]. 

### Duration and Frequency
To begin, strong ties are the ones that take up most of your time and that have lasted the longest. That is **frequency of interaction** and **tie duration** are two core subproperties that strong ties have. *Think of your the friends that you hang out with often and that you've known for a long time; those ties are strong*. 

### Support and Reciprocal Services
The other things Granovetter mentions are number of behaviors that people who have strong ties do with respect to each other. First, you can *confide* in your strong ties (tell them secrets or sensitive info about you); second people who share a strong tie *do things* for one another ("reciprocal services"). In the social networks literature these set of behaviors are known as **social support**. So you can provide support to your strong ties by listening to guarding their secrets and listening to their problems, or helping them study, or lending them twenty bucks. *So the ties that feature a heavy (two way!) reciprocal flow of services and mutual confiding are strong*.  

### Subjective Closeness
Last, and very much not least, you wouldn't be hanging out with people or keeping a tie alive for a long time, or helping them with their trials and tribulations unless you didn't have an *emotional attachment* to those people! So strong ties are those that feature (once again mutual) feelings of **subjective closeness** and that's exactly how you would describe them to a sociologist if they came asking. *Strong ties are those people in your network you feel closest to*. 

So there you have it. Strong ties are those connections you have that have lasted the longest, you interact with most frequently, feature mutual support and confiding, and you feel closest to. If a tie has all these components then it is strong for sure. If it lacks all these components, there is no question that it is weak. 

### The Tie Strength Continuum 

However, the question of whether a tie is strong or weak is not a "yes/no," or "black/white" thing. The reason for this is that while all four indicators or tie strength are *correlated* they are not deterministically linked to one another. Some ties can be high on some indicators and low in others. This is why rather than a binary there is a **tie strength continuum**. Some ties are just in-between because they contain a mixture of strong and weak components. 

For instance, there people at work you see every day but are not that subjectively close to. By the same token, there may be a friend from high school that lives in a faraway place you don't hang out with or communicate very often, but you feel very close to. These ties are "in between" strong and weak. 

Ties between parents and children also have features of both strong and weak ties. For instance, parents tend to provide their children with a lot of support (usually of the emotional and financial kind), but parents seldom (lest we get a case of the TMIs!) share their deepest sexual secrets or marital difficulties with their children (or vice versa). **Kin ties** in general (including that between siblings) tend to combine features of strong and weak ties.^[In sociology and anthropology, **kin ties** is the technical term for ties between family members. Ties to people outside the family (friends, acquaintances) are referred to as **non-kin ties**.] You usually feel subjective close to your brother or sister, but that doesn't mean you hang out with them all the time. 

Another example of a "mixed" strong/weak tie is the "love at first sight" phenomenon. Here we have a tie with very little duration (they just met!) but featuring a strong emotional feeling of closeness. Maybe the reason people find love at first sight strange or counter-intuitive is because it combines strong and weak tie properties. 

Examples could be expanded indefinitely, but the take-away point is that *most ties in social networks are not super strong or super weak, but are somewhere in between, featuring components of both strong and weak ties*. 

## Similarity 
`r newthought('Think of your closest friends and family')`. These are usually **strong ties** as we defined them in the previous section. Another overlapping property those ties have is **similarity**. That is, it is almost a "sociological law," the closest, some people think, to an actual scientific law in social science [@mcpherson21], that you are **similar**, across a wide range of dimensions, to the people you are most closely connected to. This is called the **principle of homophily** [@mcpherson01].^[For those who like their Latin derivations: *homo* means "same" and *philos* means love or attachment. Hence, homophily is "love of the same."] 

Despite the iron law of homophily, it is unlikely that you are *exactly the same* in all the ways we can think of, as every one of your close contacts. For instance, while you and your parents will likely share a residence (so you are the same in terms of living in the same place), and likely be of the same racial/ethnic background, you may not share much in terms of taste in music, movies, or humor (hence the cringe whenever your parent tells a "dad joke"). 

So when it comes to characterizing "similarity" as a core property of social ties, it is important to differentiate between the main ways two people in a social tie can be similar. *You can similar to your close contacts in one dimension, but be dissimilar in another dimension*. There are four main ways you can be similar to others that matter for the purposes of network analysis in sociology. 

### Socio-Demographic Similarity

First, you can be similar to others according to the various "socially constructed" ways that people have devised to differentiate themselves from one another. Think of the "big" anthropological constants. Every society has basic social differentiation pertaining to age (elders versus youth, parents versus children, parents versus grandparents), and the gender category assigned to people at birth (usually men versus women; but these may include other gender categories). 

In addition to these, most societies have "home made" categorical classification systems. These may include those differentiating people by occupation or trade, or those pointing to things like educational attainment (e.g., "college graduate"). In the same way, racial/ethnic classification systems are society-specific. In the U.S. for instance, when classifying people racially by skin color, we distinguish between Black and white people. However, across Latin America (e.g., Brazil), there are official racial classifications acknowledging continuous skin color distinctions "in between" Black and white. We can also come up with ways to differentiate people by economic stading, as when we talk about "upper" or "middle" class people, or the "1%". 

Overall, both the universal and home made social distinctions institutionalized and created by social authorities (e.g., the U.S. Census) to slot people into are the **socio-demographic characteristics** (sometimes also called **status characteristics**) that sociologists love to study and classify people into for purposes of research. 

Accordingly, when thinking about your most significant social ties (or not so significant "weak ties"), you can catalog the various ways in which you are socio-demographically similar or different from those others. For instance, you may have lots of different gender friends (so you are dissimilar on that socio-demographic attribute), that you share lots of others socio-demographic similarities with. This may include having the same level of education, being of the same socio-economic class background, and sharing the same racial/ethnic identity. 

**Blau Space Theory** is a network theory that says that the probability of two people sharing a tie in a social network, increases as the number of socio-demographic characteristics they have in common increases. In the same way, the theory says that as the number of socio-demographic similarities between people decreases, the probability of their having a tie decreases. This is Blau's *Principle of Sociodemographic homophily*. 

The theory is called "Blau Space" theory because it was developed by the sociologist [**Peter Blau**](https://en.wikipedia.org/wiki/Peter_Blau), who imagined that the various sociodemographic characteristics (e.g., Age, Education, Income) could be thought of as "axes" in a **social space**. If this was true, then the *distance* between two points (people) in the space is proportional to how similar they are on those characteristics. Blau's homophily principle can then be restated as saying that the probability of a social tie between people is strictly proportional to how close they are in Blau Space. The closer they are the more likely they are to be tied, and the farther away they are the less likely.

### Cultural Similarity
Another way you can be similar to the people you are connected to is by *sharing knowledge*. This includes sharing beliefs, opinions, viewpoints, tastes, preferences, and values. This is referred as **cultural similarity**. Thinking of the people you are connected to, you will be able to sort out the people you are culturally similar to, and the people you are not very culturally similar to. For instance, even though ties to kin (e.g., parents, uncles, aunts, grandparents) are generally strong, they are not necessarily culturally similar. For instance, it is unlikely you like the same movies and music your parents like, and it is also likely that there are deep differences in beliefs and opinions between you and them. On the other hand, it is very likely that you are culturally similar to friends that are close to same age.

How does this happen? Kathleen Carley's **Constructural Theory** proposes a link between **tie strength** and how culturally similar you are to the people you are connected to. More specifically Carley proposes a link between one dimension of tie strength, namely *frequency of interaction* and cultural similarity. The idea is that the more time you spend interacting with people, the more likely you are to share knowledge and beliefs with those people. This means that the more you interact, the more the overlap increases between the things you and your social contact knows. For instance, imagine all the set of things in your head (the things you know) and the set of things in your best friend's heads. These two sets are not completely identical, but there are also not completely disjoint. Instead, there's an *overlap* between them: There are some things that both of you know in common. The ratio of the things you know in common and the sum of the things that both of you know is a measure of cultural similarity. The basic idea is that when you spend time with people and share beliefs and knowledge then that overlap increases, which also increases the amount of cultural similarity between people. 

### Propinquity

The mathematical sociologist [**Carter Butts**](http://www.carterbutts.com/) has developed what can be called Butts's **the law of distance**. This says that the probability of any two people being connected by a social tie falls as a (rapidly decaying, like exponential) function of the physical distance between them. So this is another version of the "similar people are more likely to be connected" thesis but applied to propinquity as a form of similarity. The basic idea is that you tend to form ties to and interact (and perhaps become close to) those people that are most physically available to you, and those happen to be the ones that live close to you (e.g., with the limiting case being those people who live in your same house or dorm!). 

### Memberships

The sociologist [**Scott Feld**]() developed the **theory of social foci** (also known as **focus theory**) [@feld81], says that it is by coming together in contexts of interaction called *foci* that ties between people come to acquire other tie properties, like strength, (cultural) similarity, and structural embeddedness [@feld82]. 

## Structural Embededness 
`r newthought('Imagine you have a really close friend, but that friend does know or interact with any other of your close friends.')` Now imagine the same close friend who is also very close to another one of your close friends. It seems like we are talking about two very different kinds of relationships. In the first case, the tie between you and your close friend is separate from your other close (or even weak!) ties. In the second case, the tie between you and your close friend fits snuggly with the other ties between your other close friends. Social network analysts use a special word to refer to this property of social ties: **embeddedness**. 

A tie between you and a close friend who is also close with another one of your close friends is said to be **embedded** in your network. A "standalone" tie between you and someone else, regardless of how close the two of you are, is said to be **disembedded**. Note that when a tie between you and someone else is embedded, we can draw the three relationships as a **closed triad**. An embedded tie is a **connected dyad** embedded within a closed triad.^[If you know the story of Romeo and Juliet, you know that regardless of how much they loved one another, their tie was **disembedded** from their other relationships to their respective families. We know how that ended!] In general, sociologists theorize that embeddedness make strong ties even stronger.  

### Simmelian Ties
But why does embeddedness make strong ties stronger? The social network theorist [**David Krackhardt**](https://en.wikipedia.org/wiki/David_Krackhardt), drawing on the work of a turn-of-the-century German sociologist named [**Georg Simmel**](https://en.wikipedia.org/wiki/Georg_Simmel). Developed a theory that tells you why. Krackhardt calls strong ties embedded in a triads **Simmelian Ties** (in honor of Georg Simmel, who first theorized the importance of the transition from a two-person relationship to a three-person **clique**). The difference between standalone ties and embedded ties, comes down to three things.

1. If you are tied to someone but that person does not have any ties with anyone else you know, then you have more *individuality* and *independence* within that relationship. If you are tied to someone who is also tied to someone else you know you have less individuality within the three-person clique.
1. If you are tied to someone but that person does not have any ties with anyone else you know, then you have more *bargaining power* within that relationship. If you are tied to someone who is also tied to someone else you know you have less bargaining power, because the other two people can threaten to dissolve the relationship with you and keep being friends with one another. You stay alone, and they still have each other. 
1. If there is conflict within a disembedded tie, it is more difficult to fix it. Ties embedded in triads have a greater capacity for *conflict resolution* because a third person can always *mediate* the any two of the other members of the three-person clique. 

Imagine that you and your disembedded friend (who does not any one of your other friends so you are hanging out by yourselves by definition) are trying to decide where to go for dinner, but are having a hard time. You want Pizza, they want Korean Barbecue. Because each one of you have exactly one vote you are at a standstill. That means that if the whole thing escalates into an argument all you can do is shout at one another and stomp out of the room (remaining hungry or going to dinner by yourself). 

Now imagine the same situation, but it is you and your *two* other close friends. The idea is because now you are trying to decide what to do in the context of your embedded ties, the situation should play you very differently. This illustrates Krackhardt's three principles described above. First, in this situation your personal preferences and opinions count for less, because now you have to coordinate with two other people who could theoretically outvote you (if they both want Pizza your preference for Korean matters less). So the fact that you have *less bargaining power* also reduces your *individuality* in the three-person clique, forcing you toward *group conformity*. 

Now let's say you are stubborn and get into an argument with them, shouting "it's Korean or nothing!" They can just shrug, go out to dinner by themselves, leaving you angry, hungry, and alone in your room. Once again, this demonstrates the idea that you have less power within the three-person clique, because the other people always have their own relationship to fall back to. 

Finally, it could be that one of your other friends who is indifferent between Pizza and Korean helps assuage the conflict. Maybe they point out that they heard about this cool Pizza place that has Korean BBQ slices! This demonstrates the fact that ties embedded in triads have greater potential for conflict resolution via the inter-mediation of third parties.

Because of this, Krackhardt predicts that disembedded ties are more *brittle* than embedded ties. They are prone to conflict and can easily be broken without anyone helping save the relationship. Embedded ties, on the other hand, are **strong** and **sticky**. That means that most long-lasting, close ties we observe in the world should be of the embedded (Simmelian) type, not of the disembedded kind. 


- Granovetter Transitivity
- Simmelian Ties
- Number of Common Neighbors
- Structural Overlap
- Structural Segregation
- Tie Dispersion
- Tie Range
- Case Study: Can Someone Guess Who Your Facebook Significant Other Is?

## Temporal Signatures
- Tie Duration
- The Lifespan of a Tie
- The Liability of Newness
- Tie Decay and Structural Embeddedness
- Tie Freshness
- Tie Burstiness