---
title: "Status and Hierarchy"
date: "`r Sys.Date()`"
output:
  bookdown::tufte_html2: 
    tufte_variant: "envisioned"
    number_sections: true
    toc: true
bibliography: networks.bib
link-citations: yes
---
    
```{r setup, include=FALSE}
library(tufte)
      # invalidate cache when the package version changes
      knitr::opts_chunk$set(cache.extra = packageVersion('tufte'), echo = FALSE, message=FALSE, warning=FALSE)
      options(htmltools.dir.version = FALSE)
```

# Status Hierarchies
## What is Status?
`r newthought('Status, like many sociological concepts, is something that is understood intuitively yet is hard to define scientifically.')` We all know people who have “status.” We likewise often have a sense of our own status in the social world. Probably you are conscious at some level of increasing your status in the world, perhaps by attending college so that you can get a prestigious job, and receive the respect of your associates. 

While you likely have an intuitive understanding, a more precise formal definition is useful for analysis. An incredibly useful definition of status, proposed by Max Weber and later utilized by Roger @gould02, defined status as the receipt of deference. **Deference** is when someone yields to the opinion or preferences of another, despite their own preferences being different, and such yielding is unreciprocated. For example, if Friend 1 suggests one restaurant, and Friend 2 agrees despite their dislike of that restaurant, Friend 2 is sending deference to Friend 1. 

Actually existing social relations are often “give and take.” Simmel noted that relations are complex composites of repeated and varied exchange. Sometimes one friend agrees for the sake of the other friend, and that friend later reciprocates by deferring to the preferences of the other. When the yielding of ego to an alter is reciprocated, deference is not occurring. It is when there is an inequality in yielding that deference occurs. If one friend is always agreeing to go to a restaurant they dislike, while the other friend refuses to go to another restaurant, then there is inequality in the yielding, and deference is occurring.

Roger Gould proposed a useful model to explain why deference occurs. The model consists of some conception of underlying quality and deference. In Gould’s model, you can think of underlying quality in any way you find useful. The person could be talented at school, good at sports, funny, or a good friend. What matters simply is that they have higher or lower “quality” compared to other people in the network. 

If someone who is less talented wants to be friends with someone who is more talented however, they might need to “exchange” something in addition to their own quality to convince the other person to be their friend. All that person may have to exchange though is deference towards the other person. In exchange for their association, the less talented exchanges attention for the higher quality of their desired friend. This deference becomes a social signal of quality and status for the receiver, marking them as someone worth deferring to, as well as giving them more say over the terms of the relationship.

This is the underlying logic behind why sometimes friends are reluctant to ask each other if they would like to hang out. Asking if a friend would like to spend time together is inherently a sign of deference, one person is at the relational mercy of the other. If the non-asker refuses to agree, or if they never reciprocate by asking to hang out as well, then it shows relational inequality. Rather than being rejected or put at a relational disadvantage, friends will simply not ask each other to hang out, with perhaps all being worse off.

Gould also adds to the model of quality and deference a preference for reciprocity. When the preference for reciprocity is low, giving deference is not something people find objectionable. However, when the preference for reciprocity is high, then people will be highly reluctant to send deference to another. When quality in the population is heterogeneous, and the preference for reciprocity is low, there will high levels of deference and high degree inequality, while when quality is homogenous and preferences for reciprocity is high, there will be greater levels of degree equality. 

Gould’s model highlights two features of how network ties are chosen. First, some idea of an actor’s quality, and that inequalities in quality will be compensated for with deference. Second, is how much reciprocity is desired in the relationship. If the amount of deference required exceeds the amount of a lack of reciprocity that will be tolerated, then the relationship will not form. 

# Status in Valenced Interactions
`r newthought('Just like quality and reciprocity are two important aspects in tie formation,')` the structural balance of sentiments in a valanced network can also influence a node’s choice of network ties. Karma, status, and solidarity theories each predict different ways in which a valanced network balances. Imagine starting at a new high school, and having to learn where everyone stands in the social network for the first time. You don’t know much about anyone else, and the sentiments of students towards each other are already established, and you have to figure out how to now feel about all your new classmates. Karma, status, and solidarity theory help predict how you will proceed to feel about the new students. Each of the three theories elaborates on balancing dynamics to predict how an ego might feel about an alter, based on the sentiment relations between that alter and other members of the network. 

- **Karma Theory** proposes that people reciprocate the feelings that someone sends towards others. For example, if someone is just a negative person, and acts rudely towards others without apparent provocation, then one is likely to reciprocate that negativity. Similarly, is someone is kind towards you, you are likely to reciprocate this positivity. Without additional relational context, karma theory posits that we are likely to reciprocate the valance of the sentiments that others send out. Thus, from the perspective of the sender **you get what you give out**. If you send out a lot of negative towards others, you will get negative ties send *toward* you. If you send a lot positive ties to others, you will get positive ties *sent to you*.

- **Status Theory** argues that people feel towards an alter the same way others feel towards that same alter. If other people like someone, then you are more likely to also like that person. Status theory posits that people mimic the sentiments that others send towards a potential alter. Not only might we seek to align our sentiments with those around us, and thus match our feelings towards an alter with those of others so that we are not in conflict with them, but also that person might also have more information about the alter that we are making a decision to like or dislike. In the first mechanism status theory stems from balance, and in the second mechanism it stems from information asymmetry. Both mechanisms though predict that we align our sentiments towards someone with the valance of the ties that person receives.   

- **Solidarity Theory ** posits that people feel positively towards those who are similarly socially situated in a sentiment network, and negatively towards those differently situated. Imagine if two people are generally disliked in the overall network. Those two disliked people have, from a recognition of their mutual position, an incentive to like one another in contrast to the dislike they receive from the rest of the network. Similarly, if both are liked in the network, they also share a similarity in the network, and have an incentive to like one another, recognizing their still shared similarity in the network. However, if one is like by others, and the other is disliked, they no longer have a shared position. When the pattern of sentiments received is different, solidarity theory predicts that the sentiment between two people with different position in a network of valenced interactions will be negative. 

Thus, each of the three theories posits that sentiment relations are reciprocated in a manner that seeks to balance with the larger set of existing relations. Rather than having some conception of whether an ego genuinely likes an alter, the decision to like an alter or not is driven purely by balance considerations.

# Hierarchy
## Chickens
`r newthought('The structure of social relations in society can often be thought of as a hierarchy.')` A **hierarchy** is when there is a network of social relations where there is inequality in authority or deference between actors. If one person holds authority over, dominates, or has a greater ability to walk away from a relationship, then hierarchy exists between actors.   

Chickens are examples of perfectly linear hierarchies. There is a clear “pecking order” where each chicken stands transitively above or below other chickens. Transitivity means that relational hierarchy passes through nodes. Just as in math when A>B>C, by the logic of transitivity, A>C, this also applies in directed networks when it comes to hierarchy. This transitivity means that if A is above B, A is also above every actor that B is above as well. 

@chase82 examined this perfectly linear hierarchy in chickens by placing chickens in a pen and observing the hierarchy that they would form when left to sort out their own newly formed chicken society. Chickens would proceed to engage in scuffles, the winner of the fight establishing dominance over the other. The chickens would proceed to fight until a perfectly linear hierarchy was formed, with each chicken knowing its own place, and the place of the other chickens, in that hierarchy. Furthermore, the chickens would ritually reinforce the hierarchy. A chicken would “peck” the head of another chicken below it in the hierarchy. The pecked chicken would assent to this reinforcement of the hierarchy by lowering its head to receive the peck. The head chicken also was able to eat first and served as a lookout against enemies for the other chickens when they ate. 

## Humans
Likewise, humans also create hierarchies. Unlike chickens, the hierarchies that humans form are not perfectly transitive, and also can vary depending on the context. Inside the classroom, a teacher is the final authority, but outside the classroom, the authority relations are not enforceable. If you received a call from the President of the United States, you might respond with great politeness and a sense of deference, but come election time the hierarchy inverts as their position stems from the will of voters. Or maybe two people are in two clubs together, but they each have leadership positions in one of those two, meaning that in some decisions the hierarchy goes one way, and for other decisions, the hierarchy inverts. Hierarchies generally exist with actors tacitly recognizing the ordering, but they are more context-dependent and every so often there are disagreements over what factors should determine the status order. 

# Agonistic Encounters
When two actors engage in a contest for position or status, we call this an **agonistic encounter**. Whether someone insults another person, beats them in a sports match, or duels another in a battle of rhetorical wit, agonistic encounters occur when people jockey with one another for a higher position in the status ranking. Whether it is answering a question in class to demonstrate to others that you are capable, or passing on a rumor that you heard about someone at work, the ways people seek to improve their social position are quite commonplace. All of these attempts to impact the status order of a network can be thought of as agonistic encounters.

You may have heard of a game called Chicken. In Chicken, two players engage in a test of wills, where both engage in a behavior that will result in their mutual destruction if neither side turns away. However, the first person to turn away loses, the “chicken” who failed to stomach the prospect of their assured destruction. For example, if two cars drive towards one another, both will crash unless one turns away. However, being the first to turn away demonstrates cowardice compared to the winner. Agonistic encounters are largely matters of confidence, with the first person to turn away or give up being the loser. A minor dispute can continue to escalate if neither side is willing to give up, each party raising the stakes to try to defeat their opponent. However, if neither side gives up, the end result is often a physical confrontation as the last resort to settling a dispute that cannot otherwise be settled. 

Conflict takes on an aspect of performance, were demonstrating a strong commitment to not back down early can lead to a quicker defeat of an opponent. Due to the dynamic where if neither side backs down, the conflict will continue to escalate, demonstrating a willingness to continue escalation changes the calculations of an opponent, who might decide that backing down at an early stage is preferable to back down after the stakes have been raised over time. Thus, those who demonstrate a willingness to engage in high-stakes conflict typically win contests because they signal their commitment to not back down early. This can be done by outsized reactions to events and displaying unfailing confidence. 

<!--A common form of an agonistic encounter is rumors and insults. Passing on information detrimental to someone’s standing in a community is a way to drop their own social status, and to increase the status of the one spreading the rumor. The work of Faris and Felmlee (2018) explores how…. -->

## Models of Hierarchy Formation

When we think about hierarchy, often we say that those who are the “best” end up on the top of the hierarchy, and one’s talents order the rest of the hierarchy downwards, with those with more skill above those with less. This model is intuitive, and posits that the “biggest, fastest, strongest” along some dimension rise to the top of the hierarchy, and the smallest, slowest, weakest falling to the bottom. This is often how we think about nature and evolutionary processes. We might call this an **attribute-based model of hierarchy**, where some underlying aspect of a person or their ability is leveraged to determine one’s place in a hierarchy. 

In contrast to this model, there is one based on the order in which competition occurs. The **interaction-based model of hierarchy** is the idea that past status competitions have an effect on future status competitions, and whether an actor won or lost a previous contest will impact their future chances of winning or losing. 

- **Winner effects** are benefits from winning an agonistic encounter that an actor receives. Imagining a sports match, we can readily understand how winning improves one’s future chances compared to losing. Winning in the past establishes future expectations of winning by increasing the winner’s confidence. Additionally, the experience of conflict can be learned from to improve future performance in a conflict. Winners often experience a surge in testosterone, which may have a biological association with aggression and confidence. 

- **Loser effects** are penalties suffered by an actor who loses an agonistic encounter. If we imagine the same sports match, a loser might suffer a decline in confidence, lowering their chances of winning future agonistic encounters. Particularly in physical contests, a loser is more likely to suffer an injury that puts them at a disadvantage in future contests, or in a verbal contest may suffer lowered social standing, meaning that others are less likely to listen to their verbal attacks in the future. 

- **Bystander effects** are both benefits and penalties that accrue to an actor who observed, but did not participate in the agonistic encounter. Observing the outcome means that the bystander gains from the loser’s loss, while loses from the winner’s gains. While the bystander becomes weaker vis-à-vis the winner, the bystander becomes stronger in comparison to the loser. 

As a result of these effects, an interaction-based model of hierarchy notes that the final hierarchy is not a pure result of underlying abilities, but the order in which competition occurs. Imagine a situation where the first and second strongest chickens get in a fight. While the strongest may win and gain winner effects, the second strongest chicken will suffer injury or lose confidence possibly. Thus, the bystander chicken, the weakest of the three, is now able to defeat the chicken which lost the first contest, a feat the weakest chicken would previously be unable to do. As such, rather than an ideal hierarchy from strongest to weakest, hierarchy is influenced by the order in which contests occur. While of course sometimes the winners suffer injuries, and losers may not lose confidence, the model is useful for helping us think through propensities in agonistic encounters and the formation of hierarchy, rather than being perfectly predictive.   

<!--**Dominance Orders**

Transitivity in dominance configurations-->