## Weighted Ego Graphs 
```{r wegograph, echo = FALSE, warning = FALSE, message=FALSE, fig.cap = "Weighted ego graph for point D.", fig.margin = TRUE, fig.height=6}
    fr <- c(rep("D", 5), rep("A", 3), rep("B", 2), rep("C", 3), "E", "E") 
    to <- c("A", "B", "C", "E", "F", "E", "C", "B", "A", "C", "E", "A", "B", "A", "C")
    set.seed(3967)
    ec <- c(rep("ea", 5), c(rep("aa", 5)))
    nc <- c("tan1", rep("turquoise",5))
    edge.dat <- data.frame(fr, to)
    gr <- graph_from_data_frame(edge.dat, directed = FALSE)
    gr <- simplify(gr)
    set.seed(45023)
    E(gr)$weight <- round(runif(10), 2)
    p <- ggraph(gr, layout = 'star')
    p <- p + geom_edge_link(aes(colour = ec, width = weight, label = weight), 
                    angle_calc = 'along', label_size = 4.5,
                    label_dodge = unit(4, 'mm'))
    cols <- c("ea" = "steelblue", "aa" = "red")
    p <- p + scale_discrete_manual(values = cols, aesthetics = "edge_colour")
    p <- p + geom_node_point(aes(x = x, y = y), color = nc, size = 18) 
    p <- p + geom_node_text(aes(label = name), size = 8)
    p <- p + theme_graph() + ylim(-1,1.2) 
    p <- p + theme(legend.position = "none")
    p
```

Just like whole graphs can be weighted, ego graphs, can also be **weighted**. That is, rather than having the same level of communication with each of your alters, you probably prefer to communicate with some of your friends more than others, or hang out with some of your friends more often. In the same away, some of your alters may have weaker or strong connections to one another. The idea is that the **tie strength** of ego-to-alter ties and alter-to-alter ties may be different. This can be represented using a **weighted ego graph**, like the one shown in Figure \@ref(fig:wegograph).

In the Figure we can see that the ego node (*D*) has connections of different strengths with their alters, having a relatively weak tie with alter *F* and relatively strong ties with *C* and *E*. The edge weights could represent any normalized measure of intensity or frequency of interaction. In the same way, alters have connections of different strengths among themselves, with contacts *C* and *B* having a very weak tie and contacts *C* and *A* and *C* and *E* having a relatively stronger bond. We will see that various ego network metrics are defined explicitly for use with weighted ego nets, and others, while initially designed with simple ego nets in mind, can be extended to the weighted case in a straightforward way. Also, weighted ego graphs play an important role in some ego network theories, like Aral and Van Alstyne's **diversity-bandwidth trade-off theory**, to be discussed later.

## Advanced Ego Network Metrics
### Vertex Strength
### Vertex Concentration
### Weighted Clustering Coefficient
### Contact Redundancy 