<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Social Networks - 14&nbsp; From Graph to Matrix</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./8-2-lesson-special-matrices.html" rel="next">
<link href="./7-1-lesson-directed-indirect-connections.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Social Networks</span>
    </a>
  </div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">From Graph to Matrix</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./social-ties1.jpeg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-lesson-what-are-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What are Networks?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-1-lesson-graph-theory.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Graph Theory</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-2-lesson-node-neighborhoods.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nodes and their Neighborhoods</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-3-lesson-graphs-subgraphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Graphs and their Subgraphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-1-lesson-ties-and-graphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Types of Ties and Their Graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-2-lesson-dyads-and-triads.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Dyads and Triads</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-3-lesson-other-graphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Other Types of Graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-1-lesson-graph-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Basic Graph Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-2-lesson-degree-based-graph-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Degree-Based Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-lesson-directed-graph-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Directed Graph Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./6-lesson-egonet-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Ego Network Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-lesson-indirect-connections.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Indirect Connections</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./7-1-lesson-directed-indirect-connections.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Directed Indirect Connections</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-1-lesson-from-graph-to-matrix.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">From Graph to Matrix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./8-2-lesson-special-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Special Matrices</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./9-lesson-matrix-operations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Matrix Operations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-lesson-affiliation-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Affiliation Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-lesson-centrality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Centrality</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-lesson-groups-cliques.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Clique Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-lesson-positions-struct-equiv.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Equivalence and Similarity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-lesson-positions-blockmod.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Blockmodeling</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#matrices" id="toc-matrices" class="nav-link active" data-scroll-target="#matrices"><span class="toc-section-number">14.1</span>  Matrices</a>
  <ul class="collapse">
  <li><a href="#relationship-matrices" id="toc-relationship-matrices" class="nav-link" data-scroll-target="#relationship-matrices"><span class="toc-section-number">14.1.1</span>  Relationship Matrices</a></li>
  <li><a href="#diagonal-versus-off-diagonal-cells" id="toc-diagonal-versus-off-diagonal-cells" class="nav-link" data-scroll-target="#diagonal-versus-off-diagonal-cells"><span class="toc-section-number">14.1.2</span>  Diagonal versus off-diagonal cells</a></li>
  </ul></li>
  <li><a href="#adjacency-matrices-for-different-types-of-graphs" id="toc-adjacency-matrices-for-different-types-of-graphs" class="nav-link" data-scroll-target="#adjacency-matrices-for-different-types-of-graphs"><span class="toc-section-number">14.2</span>  Adjacency Matrices for Different Types of Graphs</a>
  <ul class="collapse">
  <li><a href="#the-symmetric-adjacency-matrix" id="toc-the-symmetric-adjacency-matrix" class="nav-link" data-scroll-target="#the-symmetric-adjacency-matrix"><span class="toc-section-number">14.2.1</span>  The Symmetric Adjacency Matrix</a></li>
  <li><a href="#applying-your-knowledge-calculating-average-nearest-neighbor-degree-from-the-adjacency-matrix" id="toc-applying-your-knowledge-calculating-average-nearest-neighbor-degree-from-the-adjacency-matrix" class="nav-link" data-scroll-target="#applying-your-knowledge-calculating-average-nearest-neighbor-degree-from-the-adjacency-matrix"><span class="toc-section-number">14.2.2</span>  Applying Your Knowledge: Calculating Average Nearest Neighbor Degree from the Adjacency Matrix</a></li>
  <li><a href="#the-asymmetric-adjacency-matrix" id="toc-the-asymmetric-adjacency-matrix" class="nav-link" data-scroll-target="#the-asymmetric-adjacency-matrix"><span class="toc-section-number">14.2.3</span>  The Asymmetric Adjacency Matrix</a></li>
  <li><a href="#the-valued-adjacency-matrix" id="toc-the-valued-adjacency-matrix" class="nav-link" data-scroll-target="#the-valued-adjacency-matrix"><span class="toc-section-number">14.2.4</span>  The Valued Adjacency Matrix</a></li>
  <li><a href="#the-signed-adjacency-matrix" id="toc-the-signed-adjacency-matrix" class="nav-link" data-scroll-target="#the-signed-adjacency-matrix"><span class="toc-section-number">14.2.5</span>  The Signed Adjacency Matrix</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/olizardo/networks-textbook/blob/main/8-1-lesson-from-graph-to-matrix.qmd" class="toc-action">View source</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-grtomat" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">From Graph to Matrix</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>The lessons so far have been dedicated to exploring the various ways social networks can be represented in graph form, and computing metrics directly from graphs. This lesson will focus on using a <strong>matrix</strong> as a second way of representing networks. More accurately, as noted in the first lesson, matrices are useful way to represent graphs quantitatively, which in their turn, represent networks<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>Networks represented as graphs feel quite intuitive to us. Actors are points (nodes) and links or interactions between actors are lines (edges). We feel as if we can get a good sense of the network by looking at the pictorial network diagram, with points representing actors and lines representing pairwise links between actors. Networks represented as a matrix, however, are a bit more abstract. They are far more mathematically useful however. With many tens, hundreds, thousands, or millions of nodes and edges, creating a graph with these amounts of data only results in what network analysts call a “hairball.” Nothing can be understood by looking at a picture.</p>
<section id="matrices" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="matrices"><span class="header-section-number">14.1</span> Matrices</h2>
<p>Thus, switching to representing social networks as a matrix provides us with more analytic leverage. This was a brilliant idea that first occurred to Elaine Forsyth and Leo Katz in the mid 1940s <span class="citation" data-cites="forsyth46">(<a href="#ref-forsyth46" role="doc-biblioref">Forsyth and Katz 1946</a>)</span>. When we represent the network as a matrix, we are able to efficiently calculate features of the network that we would not be able to estimate via “eyeballing.”</p>
<p>What is a matrix?<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> A <strong>matrix</strong> is, quite simply, a set of attributes that represent the values of a particular case. Breaking that explanation down, we can imagine a matrix as in <a href="#tbl-genmatrix">Table&nbsp;<span>14.1</span></a>. This common matrix, which we will refer to as an <strong>attribute-value matrix</strong>, a toy example of which is presented in <a href="#tbl-genmatrix">Table&nbsp;<span>14.1</span></a>, seems similar to a spreadsheet. Well, that is because a spreadsheet is a matrix!</p>
<div id="tbl-genmatrix" class="anchored">
<table class="table">
<caption>Table&nbsp;14.1: Example of a general matrix.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Attribute 1</th>
<th style="text-align: center;">Attribute 2</th>
<th style="text-align: center;">Attribute 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Case 1</td>
<td style="text-align: center;">Value 1</td>
<td style="text-align: center;">Value 4</td>
<td style="text-align: center;">Value 7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 2</td>
<td style="text-align: center;">Value 2</td>
<td style="text-align: center;">Value 5</td>
<td style="text-align: center;">Value 8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 3</td>
<td style="text-align: center;">Value 3</td>
<td style="text-align: center;">Value 6</td>
<td style="text-align: center;">Value 9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 4</td>
<td style="text-align: center;">Value 10</td>
<td style="text-align: center;">Value 11</td>
<td style="text-align: center;">Value 12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 5</td>
<td style="text-align: center;">Value 13</td>
<td style="text-align: center;">Value 14</td>
<td style="text-align: center;">Value 15</td>
</tr>
</tbody>
</table>
</div>
<p>The most important feature of a matrix is thus its organization into <strong>rows</strong> and <strong>columns</strong>. The number of rows and the number of columns define the <strong>dimensions</strong> of the matrix (like the length and and the width of your apartment define its dimensions in space). So when we say that a matrix is 5 <span class="math inline">\(\times\)</span> 3 when mean that it has five rows and three columns. When referring to the dimensions of matrix the rows always come first, and the columns always come second. So the more general way of saying is that the dimensions of a matrix are <em>R</em> <span class="math inline">\(\times\)</span> <em>C</em>, where <em>R</em> is the number of rows and <em>C</em> is the number of columns.</p>
<p>The <em>intersection</em> of a particular row (say row 2 in <a href="#tbl-genmatrix">Table&nbsp;<span>14.1</span></a> and a particular column (say column 3 <a href="#tbl-genmatrix">Table&nbsp;<span>14.1</span></a> defines a <strong>cell</strong> in the matrix. So when referring to a particular value in <a href="#tbl-genmatrix">Table&nbsp;<span>14.1</span></a> we would speak of the <span class="math inline">\(ij^{th}\)</span> cell in the matrix (or <span class="math inline">\(c_{ij}\)</span>), where <em>c</em> is a general stand-in for the value of a given cell, <em>i</em> a general stand-in for a given row, and <em>j</em> is a generic stand-in for a given column. We refer to <em>i</em> as the matrix <strong>row index</strong> and <em>j</em> as the matrix <strong>column index</strong>.</p>
<p>Typically, we give matrices names using boldfaced capital letters, so if we call the matrix shown in <a href="#tbl-genmatrix">Table&nbsp;<span>14.1</span></a>, matrix <strong>B</strong>, then we can refer to a specific cell in the matrix using the notation <strong>b</strong><span class="math inline">\(_{ij}\)</span> (note the lowercase), which says “the cell corresponding to row <em>i</em> and column <em>j</em> of the <strong>B</strong> matrix.”</p>
<p>Thus, in <a href="#tbl-genmatrix">Table&nbsp;<span>14.1</span></a>, cell <strong>b</strong><span class="math inline">\(_{32}\)</span> refers to the intersection between row 3 (representing case 3) and column 2 (representing attribute 2), where we can find <em>value 6</em>. For instance, let’s say cases are people and attributes are information we collected on each person (e.g., by surveying them) like their age, gender identity, and racial identification and so forth. Thus, if attribute 2 in <a href="#tbl-genmatrix">Table&nbsp;<span>14.1</span></a> was age, and case 3 was a person, then <em>value 6</em> would record that persons age (e.g., 54 years old).</p>
<section id="relationship-matrices" class="level3" data-number="14.1.1">
<h3 data-number="14.1.1" class="anchored" data-anchor-id="relationship-matrices"><span class="header-section-number">14.1.1</span> Relationship Matrices</h3>
<p>We do not generally use attribute-value matrices to represent networks. Instead, we typically use a particular type of matrix called a <strong>relationship matrix</strong>. A relationship matrix is when, instead of asking what value of an attribute a case has, we ask about the value of describing how a case relates to other cases. If attribute-value matrices relate cases to attributes, then relationship matrices relate cases to one another (which is precisely the idea behind a “network”).</p>
<p>To do that, we put the same list of cases on <em>both</em> the rows and columns the matrix. Thus, we create a matrix with the organizational properties shown in <a href="#tbl-relmatrix">Table&nbsp;<span>14.2</span></a>.</p>
<div id="tbl-relmatrix" class="anchored">
<table class="table">
<caption>Table&nbsp;14.2: Example of a relationship matrix.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Case 1</th>
<th style="text-align: center;">Case 2</th>
<th style="text-align: center;">Case 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Case 1</strong></td>
<td style="text-align: center;"><em>Value 1</em></td>
<td style="text-align: center;">Value 2</td>
<td style="text-align: center;">Value 3</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Case 2</strong></td>
<td style="text-align: center;">Value 4</td>
<td style="text-align: center;"><em>Value 5</em></td>
<td style="text-align: center;">Value 6</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Case 3</strong></td>
<td style="text-align: center;">Value 7</td>
<td style="text-align: center;">Value 8</td>
<td style="text-align: center;"><em>Value 9</em></td>
</tr>
</tbody>
</table>
</div>
<p>A relationship matrix thus captures exactly that, the relationship between two cases as shown in <a href="#tbl-relmatrix">Table&nbsp;<span>14.2</span></a>. So each cell, as the intersection of two cases (the row case and column case) gives us the value of the relationship between the cases. This value could be “friends” (if the two people are friends) or “not friends” (if they are not friends). The value could be the <strong>strength</strong> of the relationship. For instance each cell could contain the number of times a given case (e.g., a person) messaged another case.</p>
<p>Relationship matrices are different from attribute value matrices, in that the latter are typically <strong>rectangular matrices</strong>. In a rectangular matrix, the number of rows (e.g., people) can be different from the number of columns (e.g., attributes). For instance, the typical attribute-value matrix used by social scientists who collect survey data on people are typically rectangular containing many more cases (rows) and columns (attributes). Some networks, like <strong>two mode networks</strong> represented as bipartite graphs, are best studied using rectangular matrices.</p>
<p>Relationship matrices have some unique attributes. For instance, all relationship matrices are <strong>square matrices</strong>. A square matrix is one that has the <em>same number of rows and columns</em>: <span class="math inline">\(R = C\)</span>. So the relationship matrix shown in <a href="#tbl-relmatrix">Table&nbsp;<span>14.2</span></a> is <span class="math inline">\(3 \times 3\)</span>. A square matrix with <em>n</em> rows (and thus the same number of columns) is said to be a matrix of order <em>n</em>.</p>
</section>
<section id="diagonal-versus-off-diagonal-cells" class="level3" data-number="14.1.2">
<h3 data-number="14.1.2" class="anchored" data-anchor-id="diagonal-versus-off-diagonal-cells"><span class="header-section-number">14.1.2</span> Diagonal versus off-diagonal cells</h3>
<p>In a relationship matrix, we need to distinguish between two types of cells. First, there are the cells that fall along the <strong>main diagonal</strong> an imaginary line that runs from the uppermost left corner to the lowermost right corner; these are called <strong>diagonal cells</strong>, the values corresponding to which are shown in italics in <a href="#tbl-relmatrix">Table&nbsp;<span>14.2</span></a>. So if we name the matrix in <a href="#tbl-relmatrix">Table&nbsp;<span>14.2</span></a> matrix <strong>A</strong>, then we can see that any cell <strong>a</strong><span class="math inline">\(_{ij}\)</span> in which <em>i</em> = <em>j</em> falls along the main diagonal; these are Values 1, 5, and 9 <a href="#tbl-relmatrix">Table&nbsp;<span>14.2</span></a>. Every other cell in which <em>i</em> <span class="math inline">\(\neq\)</span> <em>j</em>, is an off-diagonal cell.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>In reference to the main diagonal, off-diagonal cells are said to be <em>above</em> the main diagonal if the row index for that cell is smaller than the column index (e.g., <strong>a</strong><span class="math inline">\(_{i &lt; j}\)</span>). So in <a href="#tbl-relmatrix">Table&nbsp;<span>14.2</span></a>, values 2, 3, and 6, corresponding to cells <strong>a</strong><span class="math inline">\(_{12}\)</span> <strong>a</strong><span class="math inline">\(_{13}\)</span> and <strong>a</strong><span class="math inline">\(_{23}\)</span>, respectively, are above the main diagonal. In the same way, cells in which the row index is larger than the column index are said to be <em>below</em> the main diagonal (e.g., <strong>a</strong><span class="math inline">\(_{i &gt; j}\)</span>). So in <a href="#tbl-relmatrix">Table&nbsp;<span>14.2</span></a>, values 4, 7, and 8, corresponding to cells <strong>a</strong><span class="math inline">\(_{21}\)</span> <strong>a</strong><span class="math inline">\(_{31}\)</span> and <strong>a</strong><span class="math inline">\(_{32}\)</span>, respectively, are below the main diagonal.</p>
<p>Note that in a square matrix, the values above and below the main diagonal have a “triangular” arrangement. Accordingly, sometimes we refer to these areas of a square matrix as the <strong>upper and lower triangles</strong>.</p>
<p>Note also that if the relationship matrix represents the relationship between the cases, and the cases are people in a social network, then the diagonal cells in a relationship matrix represent the relationship of people with themselves! Now if you have seen M. Night Shyamalan movies about people with split personalities, it is quite possible for people to have a rich set of relationships with themselves. Some of these may even form a social network inside a single head <span class="citation" data-cites="martin17">(<a href="#ref-martin17" role="doc-biblioref">Martin 2017</a>)</span>. But we are not psychiatrists, so we are interested primarily in <em>interpersonal</em> not <em>intrapersonal</em> relations.</p>
<div id="tbl-relmatrixnd" class="anchored">
<table class="table">
<caption>Table&nbsp;14.3: Example of a relationship matrix with blocked diagonals.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Case 1</th>
<th style="text-align: center;">Case 2</th>
<th style="text-align: center;">Case 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Case 1</strong></td>
<td style="text-align: center;"><em>–</em></td>
<td style="text-align: center;">Value 1</td>
<td style="text-align: center;">Value 2</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Case 2</strong></td>
<td style="text-align: center;">Value 3</td>
<td style="text-align: center;"><em>–</em></td>
<td style="text-align: center;">Value 4</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Case 3</strong></td>
<td style="text-align: center;">Value 5</td>
<td style="text-align: center;">Value 6</td>
<td style="text-align: center;"><em>–</em></td>
</tr>
</tbody>
</table>
</div>
<p>This means that most of the time, we can ignore the diagonal cells in relationship matrices and rewrite them as in <a href="#tbl-relmatrixnd">Table&nbsp;<span>14.3</span></a>, in which values appear only for the off-diagonal cells. So here we can see the relationship between Case 1 and Case 2 is Value 1, and the relationship between Case 2 and Case 1 is Value 3. Wait, would that mean Value 2 and 4 are the same? The answer is maybe. Depends on what <em>type of network tie</em> is being captured, as these were discussed in the lesson on graph theory. If the tie is <strong>symmetric</strong> (and thus represented in an <strong>undirected graph</strong>), then the values will have to be the same. But if the <strong>asymmetric</strong> (and thus represented in a <strong>directed graph</strong>) then they don’t have to be.</p>
<p>By convention, in a relationship matrix, we say that the case located in row <em>i</em> <strong>sends</strong> (a tie) to the case located in column <em>j</em>, so if the relationship matrix was capturing friendship, we might say that <em>i</em> considers <em>j</em> to be a friend (sends the consideration) and so if <em>i</em> is Case 1 (row 1) and <em>j</em> is Case 2 (column 2), that would be Value 1 (e.g., “Are we friends?” Value 1 = Yes/No). But when <em>i</em> is now Case 2 (row 2) and <em>j</em> is Case 1 (column 1), we are now asking if Case 2 considers Case 1 to be a friend (e.g., “Are we friends?” Value 3 = Yes/No). If friendship is considered an asymmetric tie in this case, then that could be true, or it could not be. For instance, Case 2 can rebuff Case 1’s friendship offer.</p>
<p>Note that if the tie we recorded in a relationship matrix is symmetric, we can simplify the presentation even further. The reason is that as already noted, if a relationship is symmetric, then the value of the tie that <em>i</em> sends to <em>j</em> is necessarily the same as the value of the tie that <em>j</em> sends to <em>i</em>. This means that, in the relationship matrix, the <em>value</em> of cell <strong>a</strong><span class="math inline">\(_{ij}\)</span> <em>has</em> to be the same as the value of the cell <strong>a</strong><span class="math inline">\(_{ji}\)</span> for all rows <em>i</em> and columns <em>j</em> in the matrix. This yields a <strong>symmetric relationship matrix</strong>, like that shown in <a href="#tbl-relmatrixndsymm">Table&nbsp;<span>14.4</span></a>.</p>
<div id="tbl-relmatrixndsymm" class="anchored">
<table class="table">
<caption>Table&nbsp;14.4: Example of a symmetric relationship matrix with blocked diagonals.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Case 1</th>
<th style="text-align: center;">Case 2</th>
<th style="text-align: center;">Case 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Case 1</strong></td>
<td style="text-align: center;"><em>–</em></td>
<td style="text-align: center;">Value 1</td>
<td style="text-align: center;">Value 2</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Case 2</strong></td>
<td style="text-align: center;">Value 1</td>
<td style="text-align: center;"><em>–</em></td>
<td style="text-align: center;">Value 3</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Case 3</strong></td>
<td style="text-align: center;">Value 2</td>
<td style="text-align: center;">Value 3</td>
<td style="text-align: center;"><em>–</em></td>
</tr>
</tbody>
</table>
</div>
<p>Note that a symmetric relationship matrix is simpler than its asymmetric counterpart, because now we only have to worry about <em>half</em> of the values. So before, in <a href="#tbl-relmatrixnd">Table&nbsp;<span>14.3</span></a> we had to worry about six distinct relationship values, but now we only have to worry about three. This means that, in a symmetric matrix, all the network information we need to look at is contained in either the <strong>lower triangle</strong> or the <strong>upper triangle</strong>. As we will see, in many applications, we can ignore one of the triangles altogether!</p>
<p>There are many types of relationship and attribute-value matrices as the basic principles just stated can be varied to capture different underlying facets of relationships. This lesson will cover various ways different types of networks can be best captured in a matrix form and then manipulated to produce sociologically meaningful results.</p>
</section>
</section>
<section id="adjacency-matrices-for-different-types-of-graphs" class="level2 page-columns page-full" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="adjacency-matrices-for-different-types-of-graphs"><span class="header-section-number">14.2</span> Adjacency Matrices for Different Types of Graphs</h2>
<p>The <strong>adjacency matrix</strong> is the most important, most commonly used way of representing graphs in network analysis. An adjacency matrix asks if two cases share a relationship or not. As we saw in the lesson on graph theory, two actors have a relationship, they share an edge (are <strong>adjacent</strong>) in the graph, whereas if they do not share a relationship, they do not share an edge in the graph (are <strong>non-adjacent</strong>).</p>
<section id="the-symmetric-adjacency-matrix" class="level3 page-columns page-full" data-number="14.2.1">
<h3 data-number="14.2.1" class="anchored" data-anchor-id="the-symmetric-adjacency-matrix"><span class="header-section-number">14.2.1</span> The Symmetric Adjacency Matrix</h3>
<p>If we want to build an adjacency matrix of a network, we simply list all the actors in the rows and columns, and ask if the two share a relationship in order to fill in the values. A great way of understanding this is to start with a graph and to convert it into a matrix. This is done below where the <strong>undirected graph</strong> from <a href="3-1-lesson-ties-and-graphs.html#fig-undirected">Figure&nbsp;<span>5.1</span></a> is converted into its <strong>symmetric adjacency matrix</strong> equivalent, shown in <a href="#tbl-symmadjmat">Table&nbsp;<span>14.5</span></a>.</p>
<p>The first step in building the adjacency matrix that represents the graph is to list all the nodes {A, B, C, D, E, F, G, H, I} as both a row and a column entry for each node. Next, one goes sequentially across the rows and columns, asking the question “does actor i have the relationship I am examining with actor j?” If the question asked is about the absence or presence of a relationship, 0’s and 1’s are used. If A has a relationship with B, the value 1 is marked. Otherwise, 0.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-symmadjmat" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">I</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: center;">–</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">–</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">–</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">–</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">–</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">–</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">–</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">–</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">–</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;14.5: Symmetric adjacency matrix corresponding to an undirected graph.</div></div>
</div>
</div>
<p>As we can see in <a href="#tbl-symmadjmat">Table&nbsp;<span>14.5</span></a>, A indeed has a relationship with B, so the corresponding cell is marked 1. In fact, A has a relationship with B, C, D, and E and has 1’s in each of the cells corresponding to these actors, but not with F, G, H, or I and so 0’s are in these cells.</p>
<p>But what do we do about the cells where we are theoretically supposed to ask if A has a relationship with A? As we have seen, for most sociological applications, it makes sense to just put a dash there, thus <strong>blocking the diagonals</strong>. It’s not sociologically meaningful for A to have a relationship with itself. For example, asking “Is A friends with A?” does not make much sense, but there are rare cases when it does, such as when A is a group of people and not an individual, and the relationship under examination might occur both within and between groups. As we saw before, these are called <strong>reflexive-ties</strong> or <strong>loops</strong>. But if the network is represented as a <strong>simple graph</strong> it should contain no loops.</p>
<p>After completing the first row, we ask does actor B have a relationship with actor A? Well yes, it does. In fact, we can know without even looking because if you recall, this network is defined ahead of time as reciprocal, meaning if A is friends with B, B is friends with A. We can remember this because the graph we are using is undirected. This means that the resulting matrix is going to be symmetric. <strong>Symmetric matrices</strong> are those that, when flipped along the diagonal (as shown in Figure <a href="#tbl-symmadjmat">Table&nbsp;<span>14.5</span></a>, the two sides of the matrix will be mirror images of each other.</p>
</section>
<section id="applying-your-knowledge-calculating-average-nearest-neighbor-degree-from-the-adjacency-matrix" class="level3" data-number="14.2.2">
<h3 data-number="14.2.2" class="anchored" data-anchor-id="applying-your-knowledge-calculating-average-nearest-neighbor-degree-from-the-adjacency-matrix"><span class="header-section-number">14.2.2</span> Applying Your Knowledge: Calculating Average Nearest Neighbor Degree from the Adjacency Matrix</h3>
<p>We can calculate the node metric known as <strong>average nearest neighbor degree</strong> (<span class="math inline">\(k^{nn}_i\)</span>), covered in the graph metrics lesson, from the graph’s <strong>adjacency matrix</strong> in a straightforward way.</p>
<p>Let <span class="math inline">\(k_i\)</span> be the sum of the <em>i</em><span class="math inline">\(^{th}\)</span> row in the graph adjacency matrix (<span class="math inline">\(\sum_j a_{ij}\)</span>), which gives us node <em>i</em>’s degree, which we refer to as <span class="math inline">\(k_i\)</span>. So for the other nodes in the network <em>j</em>, <em>l</em>, <em>m</em>, and so forth, the same formula gives us their degrees, which we write as <span class="math inline">\(k_j\)</span>, <span class="math inline">\(k_l\)</span>, <span class="math inline">\(k_m\)</span>, and so on. We just go to the corresponding row in the matrix and sum across the columns. Taking the <strong>row sums</strong> of the entire adjacency matrix, then this gives us the <strong>degree set</strong> of the entire graph.</p>
<p>Once we have all the degrees for each node in the graph, the calculation of each node’s average nearest neighbor degree simplifies to #<a href="#eq-annd2">Equation&nbsp;<span>14.1</span></a>:</p>
<p><span id="eq-annd2"><span class="math display">\[  
  \bar{k}_{nn(i)} = \frac{1}{k_i} \sum_i a_{ij} k_j
\tag{14.1}\]</span></span></p>
<p>Where <span class="math inline">\(a_{ij}\)</span> are cells in the adjacency matrix, so <span class="math inline">\(a_{ij} = 1\)</span> if nodes <em>i</em> and <em>j</em> are neighbors and equals zero otherwise. It is easy to see that this formula will first compute the sum of degrees of the neighbors of node <em>i</em> only (because the degrees of the nodes that are not <em>i</em>’s neighbors will be set to zero when each <span class="math inline">\(k_{j}\)</span> is multiplied by <span class="math inline">\(a_{ij}\)</span>) and then it will divide this total by <em>i</em>’s degree (<span class="math inline">\(k_i\)</span>).</p>
</section>
<section id="the-asymmetric-adjacency-matrix" class="level3 page-columns page-full" data-number="14.2.3">
<h3 data-number="14.2.3" class="anchored" data-anchor-id="the-asymmetric-adjacency-matrix"><span class="header-section-number">14.2.3</span> The Asymmetric Adjacency Matrix</h3>
<p>Conversely, a directed graph describing a network of asymmetric or anti-symmetric ties will create an <strong>asymmetric matrix</strong>. Saying a matrix is asymmetric means that the values contained in the <strong>upper and lower triangles</strong> of the matrix do not mirror each other. In other words, In an asymmetric matrix the cell values are not necessarily the same (the relationship is not necessarily equivalent) between every pair of cases.</p>
<p><a href="3-1-lesson-ties-and-graphs.html#fig-directed">Figure&nbsp;<span>5.2</span></a> shows an example directed graph. The corresponding <strong>asymmetric adjacency matrix</strong> is shown in <a href="#tbl-asymmadjmat">Table&nbsp;<span>14.6</span></a>. Note that while some relationships (such as between node A and B) are reciprocated, not all connections in the network are reciprocated. Node G sends ties to D and F, but does not receive any ties back. In the resulting matrix, A to B and B to A each have a 1 listed for the value, while G to D and G to F also have a value of 1. However, the cells corresponding to F to G and D to G each have a value of 0 because the ties are unreciprocated. These unreciprocated ties make the resulting matrix asymmetric. The two halves across the diagonal are no longer mirror images, but contain different entries.</p>
<p>Why are the ties are not reciprocated? You might remember from our lessons on types of ties and types of graphs, but it is because of the type of data that the graph and matrix are representing. For example, the matrix in <a href="#tbl-asymmadjmat">Table&nbsp;<span>14.6</span></a> and graph shown in <a href="3-1-lesson-ties-and-graphs.html#fig-directed">Figure&nbsp;<span>5.2</span></a> could represent a intramural basketball club where they ask everyone in the club who they like to have as a teammate. Not everyone could agree that they like to have one another as teammates, and the matrix and graph in <a href="3-1-lesson-ties-and-graphs.html#fig-directed">Figure&nbsp;<span>5.2</span></a> would represent that. In this case, a node like G and E look really lonely since they have nobody who wants to play with them. However, if the tie were to be about advice, such that actually G gives advice to D and F, but does not take their advice back, G (and E) now look like respected figures in the network.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-asymmadjmat" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">A</th>
<th style="text-align: left;">B</th>
<th style="text-align: left;">C</th>
<th style="text-align: left;">D</th>
<th style="text-align: left;">E</th>
<th style="text-align: left;">F</th>
<th style="text-align: left;">G</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">–</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;14.6: Asymmetric adjacency matrix corresponding to an directed graph.</div></div>
</div>
</div>
</section>
<section id="the-valued-adjacency-matrix" class="level3 page-columns page-full" data-number="14.2.4">
<h3 data-number="14.2.4" class="anchored" data-anchor-id="the-valued-adjacency-matrix"><span class="header-section-number">14.2.4</span> The Valued Adjacency Matrix</h3>
<p>Recall that weighted networks, in which the edges connecting actors have some kind of value range beyond zero one (e.g., representing the intensity of the relationship or the amount of interaction) are best represented using <strong>weighted graphs</strong>. Can we translate weighted graphs into matrix form? Yes! We can use square <strong>valued matrices</strong> to represent represent weighted graphs. A valued matrix is simply a type of square adjacency matrix where cell values could be any number. From the information on tie weights in the graph shown as Figure , we use the weight as an indication of the <strong>strength of the tie</strong> between the two actors. Thus, a tie is not simply absent or present, but falls along some scale ranging from absence to “maximum intensity,” which is a function of how the researcher thinks about the tie.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-weighted" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="8-1-lesson-from-graph-to-matrix_files/figure-html/fig-weighted-1.png" class="img-fluid figure-img" width="960"></p>
<p></p><figcaption class="figure-caption margin-caption">Figure&nbsp;14.1: A weighted graph.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>For example, your best friend might be a tie strength of 1.0, while people you are no very close to are closer to zero. However, in the middle there are all types of people who fall along the spectrum between your best friend and someone you have never seen before. It might make sense if you are trying to study social influence that people’s best friend might have more influence on their choices than their 5th closest friend. What the weights for your 5th closest friend in this weighting system is a matter of research design which can be debated, but once the weights are determined, it is simple to incorporate them into a matrix.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-weighted" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">A</th>
<th style="text-align: left;">B</th>
<th style="text-align: left;">C</th>
<th style="text-align: left;">D</th>
<th style="text-align: left;">E</th>
<th style="text-align: left;">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0.82</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">0.22</td>
<td style="text-align: left;">0.71</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0.33</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0.98</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: left;">0.58</td>
<td style="text-align: left;">0.85</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0.96</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">0.87</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: left;">0.31</td>
<td style="text-align: left;">0.39</td>
<td style="text-align: left;">0.42</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0.84</td>
<td style="text-align: left;">–</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;14.7: Adjacency matrix for a weighted graph</div></div>
</div>
</div>
<p>In the <a href="#fig-weighted">Figure&nbsp;<span>14.1</span></a> case, the theoretical maximum is represented by a weight of 1.0. This is shown in Table <a href="#tbl-weighted">Table&nbsp;<span>14.7</span></a>. Note that we follow the same procedure as that used for constructing the asymmetric adjacency matrix, only that this time, we check on the weight of the edge that actor <em>i</em> sends to actor <em>j</em>. When there is no edge between actors, we put a zero in the corresponding cell of the valued adjacency matrix as before. For instance, to fill the row corresponding to actor <em>D</em>, we see that they do not send a tie to actor <em>A</em>, so we put a zero in the cell corresponding to row 4 and column 1). We also observe that they indeed send a tie to actor <em>B</em> and the corresponding weight of this tie is 0.33, so we input that number into cell corresponding to row 4 and column 2 in the table. We continue until all the entries for actor <em>D</em> (row 4 of the valued adjacency matrix) are filled and keep on going row by row until we have covered all the actors in the network.</p>
</section>
<section id="the-signed-adjacency-matrix" class="level3 page-columns page-full" data-number="14.2.5">
<h3 data-number="14.2.5" class="anchored" data-anchor-id="the-signed-adjacency-matrix"><span class="header-section-number">14.2.5</span> The Signed Adjacency Matrix</h3>
<p><strong>Signed graphs</strong> like those discussed in the graph theory lesson, can also be represented using <strong>signed matrices</strong>. Signed matrices are just like valued matrices, with the stipulation that values are restricted to the couplet of -1 (to indicate a negative tie) and +1 to indicate a positive tie. For instance, the valued adjacency matrix for the signed graph shown in <a href="3-3-lesson-other-graphs.html#fig-signed">Figure&nbsp;<span>7.3</span></a> is shown in <a href="#tbl-signed">Table&nbsp;<span>14.8</span></a>.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-signed" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">A</th>
<th style="text-align: left;">B</th>
<th style="text-align: left;">C</th>
<th style="text-align: left;">D</th>
<th style="text-align: left;">E</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">–</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">–</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;14.8: Adjacency matrix for a signed graph.</div></div>
</div>
</div>
<p>As before each cell in the matrix encodes the sign of the relationship that goes from the row node to the column node. So we see that node <em>A</em> sends a positive ties to nodes <em>D</em> and <em>E</em> and sends negative ties to nodes <em>B</em> and <em>C</em>. This node has an equal number of negative and positive links. This contrasts to the row representing node <em>E</em>, which shows that they send <em>negative</em> links to all the other nodes in the graph. Perhaps they are a difficult person or some kind of downer. Reading across the rows tell us something about what each actors “gives off” in the network of valenced relations. This could be positivity or negativity. Reading across the columns, on the other hand, tell us what each actors <strong>receives</strong> from others in the network. For instance, node <em>B</em> receives negative links from every other node in the graph, making them the only universally disliked actor in the system. Meanwhile, while <em>E</em> gives off all negative links, they receive mostly positive links except for the one coming from node <em>B</em>.</p>
<p><a href="#tbl-terms">Table&nbsp;<span>14.9</span></a> summarizes the linkage between the different types of graphs and the different types of matrices used to represent them.</p>
<div id="tbl-terms" class="anchored">
<table class="table">
<caption>Table&nbsp;14.9: Specific Terms Referring to Graphs and Matrices based on the type of tie and associated network we are studying. Keep them straight!</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Type of Tie</th>
<th style="text-align: center;">Graph</th>
<th style="text-align: center;">Adjacency Matrix</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Symmetric</td>
<td style="text-align: center;">Undirected</td>
<td style="text-align: center;">Symmetric</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asymmetric</td>
<td style="text-align: center;">Directed</td>
<td style="text-align: center;">Asymmetric</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Weighted</td>
<td style="text-align: center;">Weighted</td>
<td style="text-align: center;">Valued</td>
</tr>
<tr class="even">
<td style="text-align: left;">Valenced</td>
<td style="text-align: center;">Signed</td>
<td style="text-align: center;">Signed</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-forsyth46" class="csl-entry" role="doc-biblioentry">
Forsyth, Elaine, and Leo Katz. 1946. <span>“A Matrix Approach to the Analysis of Sociometric Data: Preliminary Report.”</span> <em>Sociometry</em> 9 (4): 340–47.
</div>
<div id="ref-martin17" class="csl-entry" role="doc-biblioentry">
Martin, John Levi. 2017. <span>“The Structure of Node and Edge Generation in a Delusional Social Network.”</span> <em>Journal of Social Structure</em> 18 (1): 1–21.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Flashback to the <strong>three-step network shuffle</strong>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Note that the answer to this question is simpler than the more profound: “What is <em>the</em> Matrix?” <a href="https://www.youtube.com/watch?v=O5b0ZxUWNf0">https://www.youtube.com/watch?v=O5b0ZxUWNf0</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The mathematical symbol for “does not equal” is <span class="math inline">\(\neq\)</span>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./7-1-lesson-directed-indirect-connections.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Directed Indirect Connections</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./8-2-lesson-special-matrices.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Special Matrices</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>