<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Social Networks - 12&nbsp; Introduction to Matrices</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./lesson-matrix-adjacency.html" rel="next">
<link href="./lesson-graphs-connectivity.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Social Networks</span>
    </a>
  </div>
          <div class="quarto-toggle-container ms-auto">
              <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
          </div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Introduction to Matrices</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./social-ties1.jpeg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Introduction to Networks</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-what-are-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What Are Networks?</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Graph Theory: The Basics</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-theory.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to Graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-subgraphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Graphs and their Subgraphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-ties.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Types of Ties and Their Graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic Graph Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-neighborhoods.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Nodes and their Neighborhoods</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-degree.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Nodes and their Degrees</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-degree-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Degree-Based Graph Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-paths.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Indirect Connections</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-directed-paths.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Directed Indirect Connections</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-connectivity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Graph Connectivity</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Matrices: The Basics</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-matrix-intro.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Introduction to Matrices</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-matrix-adjacency.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Adjacency Matrix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-matrix-row-column-sums.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Matrix Operations: Row and Column Sums</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-matrix-operations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Basic Matrix Operations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-matrix-multiplication.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Matrix Multiplication</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Notions of Node Position</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-theory-equivalence.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Equivalence and Similarity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-sna-local-similarity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Local Node Similarities</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-sna-blockmodeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Blockmodeling</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-sna-centrality.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Centrality</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-sna-status.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Status</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Two-Mode Networks</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-nets-affiliation-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Affiliation Networks</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#matrices" id="toc-matrices" class="nav-link active" data-scroll-target="#matrices"><span class="toc-section-number">12.1</span>  Matrices</a>
  <ul class="collapse">
  <li><a href="#relationship-matrices" id="toc-relationship-matrices" class="nav-link" data-scroll-target="#relationship-matrices"><span class="toc-section-number">12.1.1</span>  Relationship Matrices</a></li>
  <li><a href="#diagonal-versus-off-diagonal-cells" id="toc-diagonal-versus-off-diagonal-cells" class="nav-link" data-scroll-target="#diagonal-versus-off-diagonal-cells"><span class="toc-section-number">12.1.2</span>  Diagonal versus off-diagonal cells</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/olizardo/networks-textbook/blob/main/lesson-matrix-intro.qmd" class="toc-action">View source</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-introtomat" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Introduction to Matrices</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>The lessons so far have been dedicated to exploring the various ways social networks can be represented in graph form, and computing metrics directly from graphs. This lesson will focus on using a <strong>matrix</strong> as a second way of representing networks. More accurately, as noted in <a href="lesson-what-are-networks.html"><span>Chapter&nbsp;1</span></a>, matrices are useful way to represent graphs quantitatively, which in their turn, represent networks (flashback to the <strong>three-step network shuffle</strong>).</p>
<p>Networks represented as graphs feel quite intuitive to us. Actors are points (nodes) and links or interactions between actors are lines (edges). We feel as if we can get a good sense of the network by looking at the pictorial network diagram, with points representing actors and lines representing pairwise links between actors.</p>
<p>Networks represented as a matrix, however, are a bit more abstract. They are far more mathematically useful however. With many tens, hundreds, thousands, or millions of nodes and edges, creating a graph with these amounts of data only results in what network analysts call a “hairball.” Nothing can be understood by looking at such a picture.</p>
<section id="matrices" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="matrices"><span class="header-section-number">12.1</span> Matrices</h2>
<p>Thus, switching to representing social networks as a matrix provides us with more analytic leverage. This was a brilliant idea that first occurred to Elaine Forsyth and Leo Katz in the mid 1940s <span class="citation" data-cites="forsyth46">(<a href="#ref-forsyth46" role="doc-biblioref">Forsyth and Katz 1946</a>)</span>. When we represent the network as a matrix, we are able to efficiently calculate features of the network that we would not be able to estimate via “eyeballing.”</p>
<p>What is a matrix?<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> A <strong>matrix</strong> is, quite simply, a set of attributes that represent the values of a particular case. Breaking that explanation down, we can imagine a matrix as in <a href="#tbl-genmatrix">Table&nbsp;<span>12.1</span></a>. This common matrix, which we will refer to as an <strong>attribute-value matrix</strong>, a toy example of which is presented in <a href="#tbl-genmatrix">Table&nbsp;<span>12.1</span></a>, seems similar to a spreadsheet. Well, that is because a spreadsheet is a matrix!</p>
<div id="tbl-genmatrix" class="anchored">
<table class="table">
<caption>Table&nbsp;12.1: Example of a general matrix.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Attribute 1</th>
<th style="text-align: center;">Attribute 2</th>
<th style="text-align: center;">Attribute 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Case 1</td>
<td style="text-align: center;">Value 1</td>
<td style="text-align: center;">Value 4</td>
<td style="text-align: center;">Value 7</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 2</td>
<td style="text-align: center;">Value 2</td>
<td style="text-align: center;">Value 5</td>
<td style="text-align: center;">Value 8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 3</td>
<td style="text-align: center;">Value 3</td>
<td style="text-align: center;">Value 6</td>
<td style="text-align: center;">Value 9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Case 4</td>
<td style="text-align: center;">Value 10</td>
<td style="text-align: center;">Value 11</td>
<td style="text-align: center;">Value 12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Case 5</td>
<td style="text-align: center;">Value 13</td>
<td style="text-align: center;">Value 14</td>
<td style="text-align: center;">Value 15</td>
</tr>
</tbody>
</table>
</div>
<p>The most important feature of a matrix is thus its organization into <strong>rows</strong> and <strong>columns</strong>. The number of rows and the number of columns define the <strong>dimensions</strong> of the matrix (like the length and and the width of your apartment define its dimensions in space). So when we say that a matrix is 5 <span class="math inline">\(\times\)</span> 3 when mean that it has five rows and three columns. When referring to the dimensions of matrix the rows always come first, and the columns always come second. So the more general way of saying is that the dimensions of a matrix are <em>R</em> <span class="math inline">\(\times\)</span> <em>C</em>, where <em>R</em> is the number of rows and <em>C</em> is the number of columns.</p>
<p>The <em>intersection</em> of a particular row (say row 2 in <a href="#tbl-genmatrix">Table&nbsp;<span>12.1</span></a> and a particular column (say column 3 <a href="#tbl-genmatrix">Table&nbsp;<span>12.1</span></a> defines a <strong>cell</strong> in the matrix. So when referring to a particular value in <a href="#tbl-genmatrix">Table&nbsp;<span>12.1</span></a> we would speak of the <span class="math inline">\(ij^{th}\)</span> cell in the matrix (or <span class="math inline">\(c_{ij}\)</span>), where <em>c</em> is a general stand-in for the value of a given cell, <em>i</em> a general stand-in for a given row, and <em>j</em> is a generic stand-in for a given column. We refer to <em>i</em> as the matrix <strong>row index</strong> and <em>j</em> as the matrix <strong>column index</strong>.</p>
<p>Typically, we give matrices names using boldfaced capital letters, so if we call the matrix shown in <a href="#tbl-genmatrix">Table&nbsp;<span>12.1</span></a>, matrix <strong>B</strong>, then we can refer to a specific cell in the matrix using the notation <strong>b</strong><span class="math inline">\(_{ij}\)</span> (note the lowercase), which says “the cell corresponding to row <em>i</em> and column <em>j</em> of the <strong>B</strong> matrix.”</p>
<p>Thus, in <a href="#tbl-genmatrix">Table&nbsp;<span>12.1</span></a>, cell <strong>b</strong><span class="math inline">\(_{32}\)</span> refers to the intersection between row 3 (representing case 3) and column 2 (representing attribute 2), where we can find <em>value 6</em>. For instance, let’s say cases are people and attributes are information we collected on each person (e.g., by surveying them) like their age, gender identity, and racial identification and so forth. Thus, if attribute 2 in <a href="#tbl-genmatrix">Table&nbsp;<span>12.1</span></a> was age, and case 3 was a person, then <em>value 6</em> would record that persons age (e.g., 54 years old).</p>
<section id="relationship-matrices" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="relationship-matrices"><span class="header-section-number">12.1.1</span> Relationship Matrices</h3>
<p>We do not generally use attribute-value matrices to represent networks. Instead, we typically use a particular type of matrix called a <strong>relationship matrix</strong>. A relationship matrix is when, instead of asking what value of an attribute a case has, we ask about the value of describing how a case relates to other cases. If attribute-value matrices relate cases to attributes, then relationship matrices relate cases to one another (which is precisely the idea behind a “network”).</p>
<p>To do that, we put the same list of cases on <em>both</em> the rows and columns the matrix. Thus, we create a matrix with the organizational properties shown in <a href="#tbl-relmatrix">Table&nbsp;<span>12.2</span></a>.</p>
<div id="tbl-relmatrix" class="anchored">
<table class="table">
<caption>Table&nbsp;12.2: Example of a relationship matrix.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Case 1</th>
<th style="text-align: center;">Case 2</th>
<th style="text-align: center;">Case 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Case 1</strong></td>
<td style="text-align: center;"><em>Value 1</em></td>
<td style="text-align: center;">Value 2</td>
<td style="text-align: center;">Value 3</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Case 2</strong></td>
<td style="text-align: center;">Value 4</td>
<td style="text-align: center;"><em>Value 5</em></td>
<td style="text-align: center;">Value 6</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Case 3</strong></td>
<td style="text-align: center;">Value 7</td>
<td style="text-align: center;">Value 8</td>
<td style="text-align: center;"><em>Value 9</em></td>
</tr>
</tbody>
</table>
</div>
<p>A relationship matrix thus captures exactly that, the relationship between two cases as shown in <a href="#tbl-relmatrix">Table&nbsp;<span>12.2</span></a>. So each cell, as the intersection of two cases (the row case and column case) gives us the value of the relationship between the cases. This value could be “friends” (if the two people are friends) or “not friends” (if they are not friends). The value could be the <strong>strength</strong> of the relationship. For instance each cell could contain the number of times a given case (e.g., a person) messaged another case.</p>
<p>Relationship matrices are different from attribute value matrices, in that the latter are typically <strong>rectangular matrices</strong>. In a rectangular matrix, the number of rows (e.g., people) can be different from the number of columns (e.g., attributes). For instance, the typical attribute-value matrix used by social scientists who collect survey data on people are typically rectangular containing many more cases (rows) and columns (attributes). Some networks, like <strong>two mode networks</strong> represented as bipartite graphs, are best studied using rectangular matrices.</p>
<p>Relationship matrices have some unique attributes. For instance, all relationship matrices are <strong>square matrices</strong>. A square matrix is one that has the <em>same number of rows and columns</em>: <span class="math inline">\(R = C\)</span>. So the relationship matrix shown in <a href="#tbl-relmatrix">Table&nbsp;<span>12.2</span></a> is <span class="math inline">\(3 \times 3\)</span>. A square matrix with <em>n</em> rows (and thus the same number of columns) is said to be a matrix of order <em>n</em>.</p>
</section>
<section id="diagonal-versus-off-diagonal-cells" class="level3" data-number="12.1.2">
<h3 data-number="12.1.2" class="anchored" data-anchor-id="diagonal-versus-off-diagonal-cells"><span class="header-section-number">12.1.2</span> Diagonal versus off-diagonal cells</h3>
<p>In a relationship matrix, we need to distinguish between two types of cells. First, there are the cells that fall along the <strong>main diagonal</strong> an imaginary line that runs from the uppermost left corner to the lowermost right corner; these are called <strong>diagonal cells</strong>, the values corresponding to which are shown in italics in <a href="#tbl-relmatrix">Table&nbsp;<span>12.2</span></a>. So if we name the matrix in <a href="#tbl-relmatrix">Table&nbsp;<span>12.2</span></a> matrix <strong>A</strong>, then we can see that any cell <strong>a</strong><span class="math inline">\(_{ij}\)</span> in which <em>i</em> = <em>j</em> falls along the main diagonal; these are Values 1, 5, and 9 <a href="#tbl-relmatrix">Table&nbsp;<span>12.2</span></a>. Every other cell in which <em>i</em> <span class="math inline">\(\neq\)</span> <em>j</em>, is an off-diagonal cell.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>In reference to the main diagonal, off-diagonal cells are said to be <em>above</em> the main diagonal if the row index for that cell is smaller than the column index (e.g., <strong>a</strong><span class="math inline">\(_{i &lt; j}\)</span>). So in <a href="#tbl-relmatrix">Table&nbsp;<span>12.2</span></a>, values 2, 3, and 6, corresponding to cells <strong>a</strong><span class="math inline">\(_{12}\)</span> <strong>a</strong><span class="math inline">\(_{13}\)</span> and <strong>a</strong><span class="math inline">\(_{23}\)</span>, respectively, are above the main diagonal. In the same way, cells in which the row index is larger than the column index are said to be <em>below</em> the main diagonal (e.g., <strong>a</strong><span class="math inline">\(_{i &gt; j}\)</span>). So in <a href="#tbl-relmatrix">Table&nbsp;<span>12.2</span></a>, values 4, 7, and 8, corresponding to cells <strong>a</strong><span class="math inline">\(_{21}\)</span> <strong>a</strong><span class="math inline">\(_{31}\)</span> and <strong>a</strong><span class="math inline">\(_{32}\)</span>, respectively, are below the main diagonal.</p>
<p>Note that in a square matrix, the values above and below the main diagonal have a “triangular” arrangement. Accordingly, sometimes we refer to these areas of a square matrix as the <strong>upper and lower triangles</strong>.</p>
<p>Note also that if the relationship matrix represents the relationship between the cases, and the cases are people in a social network, then the diagonal cells in a relationship matrix represent the relationship of people with themselves! Now if you have seen M. Night Shyamalan movies about people with split personalities, it is quite possible for people to have a rich set of relationships with themselves. Some of these may even form a social network inside a single head <span class="citation" data-cites="martin17">(<a href="#ref-martin17" role="doc-biblioref">Martin 2017</a>)</span>. But we are not psychiatrists, so we are interested primarily in <em>interpersonal</em> not <em>intrapersonal</em> relations.</p>
<div id="tbl-relmatrixnd" class="anchored">
<table class="table">
<caption>Table&nbsp;12.3: Example of a relationship matrix with blocked diagonals.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Case 1</th>
<th style="text-align: center;">Case 2</th>
<th style="text-align: center;">Case 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Case 1</strong></td>
<td style="text-align: center;"><em>–</em></td>
<td style="text-align: center;">Value 1</td>
<td style="text-align: center;">Value 2</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Case 2</strong></td>
<td style="text-align: center;">Value 3</td>
<td style="text-align: center;"><em>–</em></td>
<td style="text-align: center;">Value 4</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Case 3</strong></td>
<td style="text-align: center;">Value 5</td>
<td style="text-align: center;">Value 6</td>
<td style="text-align: center;"><em>–</em></td>
</tr>
</tbody>
</table>
</div>
<p>This means that most of the time, we can ignore the diagonal cells in relationship matrices and rewrite them as in <a href="#tbl-relmatrixnd">Table&nbsp;<span>12.3</span></a>, in which values appear only for the off-diagonal cells. So here we can see the relationship between Case 1 and Case 2 is Value 1, and the relationship between Case 2 and Case 1 is Value 3. Wait, would that mean Value 2 and 4 are the same? The answer is maybe. Depends on what <em>type of network tie</em> is being captured, as these were discussed in the lesson on graph theory. If the tie is <strong>symmetric</strong> (and thus represented in an <strong>undirected graph</strong>), then the values will have to be the same. But if the <strong>asymmetric</strong> (and thus represented in a <strong>directed graph</strong>) then they don’t have to be.</p>
<p>By convention, in a relationship matrix, we say that the case located in row <em>i</em> <strong>sends</strong> (a tie) to the case located in column <em>j</em>, so if the relationship matrix was capturing friendship, we might say that <em>i</em> considers <em>j</em> to be a friend (sends the consideration) and so if <em>i</em> is Case 1 (row 1) and <em>j</em> is Case 2 (column 2), that would be Value 1 (e.g., “Are we friends?” Value 1 = Yes/No). But when <em>i</em> is now Case 2 (row 2) and <em>j</em> is Case 1 (column 1), we are now asking if Case 2 considers Case 1 to be a friend (e.g., “Are we friends?” Value 3 = Yes/No). If friendship is considered an asymmetric tie in this case, then that could be true, or it could not be. For instance, Case 2 can rebuff Case 1’s friendship offer.</p>
<p>Note that if the tie we recorded in a relationship matrix is symmetric, we can simplify the presentation even further. The reason is that as already noted, if a relationship is symmetric, then the value of the tie that <em>i</em> sends to <em>j</em> is necessarily the same as the value of the tie that <em>j</em> sends to <em>i</em>. This means that, in the relationship matrix, the <em>value</em> of cell <strong>a</strong><span class="math inline">\(_{ij}\)</span> <em>has</em> to be the same as the value of the cell <strong>a</strong><span class="math inline">\(_{ji}\)</span> for all rows <em>i</em> and columns <em>j</em> in the matrix. This yields a <strong>symmetric relationship matrix</strong>, like that shown in <a href="#tbl-relmatrixndsymm">Table&nbsp;<span>12.4</span></a>.</p>
<div id="tbl-relmatrixndsymm" class="anchored">
<table class="table">
<caption>Table&nbsp;12.4: Example of a symmetric relationship matrix with blocked diagonals.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Case 1</th>
<th style="text-align: center;">Case 2</th>
<th style="text-align: center;">Case 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Case 1</strong></td>
<td style="text-align: center;"><em>–</em></td>
<td style="text-align: center;">Value 1</td>
<td style="text-align: center;">Value 2</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Case 2</strong></td>
<td style="text-align: center;">Value 1</td>
<td style="text-align: center;"><em>–</em></td>
<td style="text-align: center;">Value 3</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Case 3</strong></td>
<td style="text-align: center;">Value 2</td>
<td style="text-align: center;">Value 3</td>
<td style="text-align: center;"><em>–</em></td>
</tr>
</tbody>
</table>
</div>
<p>Note that a symmetric relationship matrix is simpler than its asymmetric counterpart, because now we only have to worry about <em>half</em> of the values. So before, in <a href="#tbl-relmatrixnd">Table&nbsp;<span>12.3</span></a> we had to worry about six distinct relationship values, but now we only have to worry about three. This means that, in a symmetric matrix, all the network information we need to look at is contained in either the <strong>lower triangle</strong> or the <strong>upper triangle</strong>. As we will see, in many applications, we can ignore one of the triangles altogether!</p>
<p>There are many types of relationship and attribute-value matrices as the basic principles just stated can be varied to capture different underlying facets of relationships. Subsequent lessons will cover various ways different aspects of networks can be best captured in matrix form and then manipulated to produce sociologically meaningful results.</p>
</section>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-forsyth46" class="csl-entry" role="doc-biblioentry">
Forsyth, Elaine, and Leo Katz. 1946. <span>“A Matrix Approach to the Analysis of Sociometric Data: Preliminary Report.”</span> <em>Sociometry</em> 9 (4): 340–47.
</div>
<div id="ref-martin17" class="csl-entry" role="doc-biblioentry">
Martin, John Levi. 2017. <span>“The Structure of Node and Edge Generation in a Delusional Social Network.”</span> <em>Journal of Social Structure</em> 18 (1): 1–21.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Note that the answer to this question is simpler than the more profound: “What is <em>the</em> Matrix?” <a href="https://www.youtube.com/watch?v=O5b0ZxUWNf0">https://www.youtube.com/watch?v=O5b0ZxUWNf0</a><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The mathematical symbol for “does not equal” is <span class="math inline">\(\neq\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./lesson-graphs-connectivity.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Graph Connectivity</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./lesson-matrix-adjacency.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Adjacency Matrix</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>