<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Social Networks - 19&nbsp; Centrality</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./lesson-status.html" rel="next">
<link href="./lesson-affiliation-networks.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Social Networks</span>
    </a>
  </div>
          <div class="quarto-toggle-container ms-auto">
              <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
          </div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Centrality</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./social-ties1.jpeg" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Introduction to Networks</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-what-are-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">What Are Networks?</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Basic Graph Theory</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graph-theory.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Graph Theory</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-node-neighborhoods.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Nodes and their Neighborhoods</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graphs-subgraphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Graphs and their Subgraphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-graph-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic Graph Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-from-graph-to-matrix.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">From Graph to Matrix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-indirect-connections.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Indirect Connections</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Advanced Graph Theory</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-ties-and-graphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Types of Ties and Their Graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-dyads-and-triads.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Dyads and Triads</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-degree-based-graph-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Degree-Based Graph Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-directed-graph-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Directed Graph Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-directed-indirect-connections.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Directed Indirect Connections</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-other-graphs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Other Types of Graphs</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Networks and Matrices</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-special-matrices.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Special Matrices</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-matrix-operations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Matrix Operations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-applied-matrix-operations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Applied Matrix Operations</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Special Kinds of Networks</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-egonet-metrics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Ego Network Metrics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-affiliation-networks.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Affiliation Networks</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">Analyzing Networks</span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-centrality.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Centrality</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-status.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Status</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-groups-cliques.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Clique Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-positions-struct-equiv.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Equivalence and Similarity</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./lesson-positions-blockmod.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Blockmodeling</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-big-three-centrality-metrics" id="toc-the-big-three-centrality-metrics" class="nav-link active" data-scroll-target="#the-big-three-centrality-metrics"><span class="toc-section-number">19.1</span>  The “big three” centrality metrics</a></li>
  <li><a href="#the-star-graph" id="toc-the-star-graph" class="nav-link" data-scroll-target="#the-star-graph"><span class="toc-section-number">19.2</span>  The Star Graph</a></li>
  <li><a href="#degree-centrality" id="toc-degree-centrality" class="nav-link" data-scroll-target="#degree-centrality"><span class="toc-section-number">19.3</span>  Degree Centrality</a>
  <ul class="collapse">
  <li><a href="#how-to-read-equations-for-matrix-operations" id="toc-how-to-read-equations-for-matrix-operations" class="nav-link" data-scroll-target="#how-to-read-equations-for-matrix-operations"><span class="toc-section-number">19.3.1</span>  How to Read Equations for Matrix Operations</a></li>
  </ul></li>
  <li><a href="#indegree-and-outdegree-centrality" id="toc-indegree-and-outdegree-centrality" class="nav-link" data-scroll-target="#indegree-and-outdegree-centrality"><span class="toc-section-number">19.4</span>  Indegree and Outdegree Centrality</a>
  <ul class="collapse">
  <li><a href="#sec-normdeg" id="toc-sec-normdeg" class="nav-link" data-scroll-target="#sec-normdeg"><span class="toc-section-number">19.4.1</span>  Normalized Degree Centrality</a></li>
  </ul></li>
  <li><a href="#closeness-centrality" id="toc-closeness-centrality" class="nav-link" data-scroll-target="#closeness-centrality"><span class="toc-section-number">19.5</span>  Closeness Centrality</a></li>
  <li><a href="#houston-we-have-a-problem" id="toc-houston-we-have-a-problem" class="nav-link" data-scroll-target="#houston-we-have-a-problem"><span class="toc-section-number">19.6</span>  Houston, We Have a Problem</a></li>
  <li><a href="#betweenness-centrality" id="toc-betweenness-centrality" class="nav-link" data-scroll-target="#betweenness-centrality"><span class="toc-section-number">19.7</span>  Betweenness Centrality</a></li>
  <li><a href="#the-big-three-centralities-in-the-star-graph" id="toc-the-big-three-centralities-in-the-star-graph" class="nav-link" data-scroll-target="#the-big-three-centralities-in-the-star-graph"><span class="toc-section-number">19.8</span>  The Big Three Centralities in the Star Graph</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/olizardo/networks-textbook/blob/main/lesson-centrality.qmd" class="toc-action">View source</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-centrality" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Centrality</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>What is centrality? In terms of graph theory, a <strong>centrality metric</strong> is a summary index of a node’s position in a graph, based on (sometimes weighted) <em>sums</em> or <em>averages</em> of one of three things <span class="citation" data-cites="borgatti_everett06">(<a href="#ref-borgatti_everett06" role="doc-biblioref">Borgatti and Everett 2006</a>)</span>:</p>
<ol type="1">
<li>The <em>number</em> of <strong>edges</strong> that are directly <strong>incident</strong> upon that node.</li>
<li>The <em>length</em> of (usually <strong>shortest</strong>) <strong>paths</strong><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> that have that node as one of their <strong>end nodes</strong>.</li>
<li>The <em>proportion</em> of (usually <strong>shortest</strong>) <strong>paths</strong><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> that have that node as one their <strong>inner nodes</strong>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></li>
</ol>
<p>The basic idea behind all centrality metrics is based on the <strong>more/more principle</strong>. This is the idea that <em>the higher any of the things above is for a node, then the more central that node is in the graph</em>. So a node with more nodes incident upon it (the size of the neighbor set) should be more central. In the same way, a node who can <strong>reach</strong> many other nodes via the smallest shortest paths, should be more central. Finally, a node standing in the middle of the largest percentage of paths between other nodes should be more central, and so forth.</p>
<p>We can refer to all these things as <strong>network goods</strong>. The more/principle has a basic measurement implication, which is that centrality should never <em>decrease</em> when a node gains access to more network goods (e.g., one an additional connection) in the network. The <strong>more/more centrality principle</strong> was described by legendary social network theorist <a href="https://www.socsci.uci.edu/newsevents/news/2018/2018-08-23-freeman.php"><strong>Linton Freeman</strong></a> in a classic paper <span class="citation" data-cites="freeman79">(<a href="#ref-freeman79" role="doc-biblioref">Freeman 1979</a>.)</span></p>
<p>Sociologically, the notion of centrality is tied to such concepts as “status,” “prestige,” “importance,” “influence,” “popularity,” “reachability,” “brokerage,” and many more. So the more central nodes have higher status, are more popular, influential, broker more deals, and so forth. However, these english language descriptors map onto distinct metrics. For instance, “popularity” clearly has to do with the number of connections a node has. <em>Brokerage</em>, on the other hand, has more to do with a node stand in-between paths linking others nodes. Influence, on the other hand, seems to have more to do with the capacity to reach others, and so forth.</p>
<p>Accordingly, all these sociological concepts related to centrality have to be kept distinct from any one centrality metric (remember the <strong>three-step shuffle</strong> in social network analysis discussed earlier), because the same concept can be measured by more than one centrality metric, and the same metric can point to many distinct sociological concepts, depending on the context, the type of social ties the network is constructed from, and the way either “goods” (e.g., information, advice, support, etc.) or “bads” (e.g., disease, gossip, violence etc.) “flow” through the network <span class="citation" data-cites="borgatti05">(<a href="#ref-borgatti05" role="doc-biblioref">Borgatti 2005</a>)</span>.</p>
<section id="the-big-three-centrality-metrics" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="the-big-three-centrality-metrics"><span class="header-section-number">19.1</span> The “big three” centrality metrics</h2>
<p>Linton <span class="citation" data-cites="freeman79">Freeman (<a href="#ref-freeman79" role="doc-biblioref">1979</a>)</span>, in the aforementioned paper, defined the “big three” classic centrality metrics, roughly corresponding to the extent that a node accumulates one of the three network goods mentioned above. - So the <strong>degree centrality</strong> metric deal with nodes that have more edges directly incident upon them <span class="citation" data-cites="nieminen74">(<a href="#ref-nieminen74" role="doc-biblioref">Nieminen 1974</a>)</span>. - The <strong>closeness centrality</strong> metric has to do with nodes that can reach more nodes via smallest <strong>shortest paths</strong> and thus accumulate as many of these paths in which they figure as the <strong>origin node</strong> as possible <span class="citation" data-cites="sabidussi66">(<a href="#ref-sabidussi66" role="doc-biblioref">Sabidussi 1966</a>)</span>. - Finally, the <strong>betweenness centrality</strong> metric has to do with a node’s accumulation of the largest share of shortest paths in which they intermediate between two other nodes, and thus featuring them as one of the <strong>inner nodes</strong> in the paths between others <span class="citation" data-cites="freeman77">(<a href="#ref-freeman77" role="doc-biblioref">Freeman 1977</a>)</span>.</p>
<p>Other centrality metrics can be seen as generalizations or special cases of any of these three basic notions <span class="citation" data-cites="borgatti05">(<a href="#ref-borgatti05" role="doc-biblioref">Borgatti 2005</a>)</span>.</p>
<p>The rest of the lesson goes over the basic interpretation and calculation (using the graph theory and matrix algebra tools discussed in previous lessons) of “big three” centrality metrics.</p>
</section>
<section id="the-star-graph" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="the-star-graph"><span class="header-section-number">19.2</span> The Star Graph</h2>
<p>Freeman showed that the three basic measures reach their theoretical <em>maximum</em> for the central node in a <strong>star graph</strong>, such as the one shown in <a href="#fig-star">Figure&nbsp;<span>19.1</span></a>).</p>
<div class="cell" data-fig-cap-location="margin">
<div class="cell-output-display">
<div id="fig-star" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lesson-centrality_files/figure-html/fig-star-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;19.1: A star graph</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>A star graph is a graph containing a <strong>central</strong> or <strong>inner</strong> node (in <a href="#fig-star">Figure&nbsp;<span>19.1</span></a>, node <em>A</em>), who is connected to all the other nodes in the graph, called the <strong>satellite</strong> or <strong>outer</strong> nodes (in <a href="#fig-star">Figure&nbsp;<span>19.1</span></a>, nodes <em>B</em> through <em>F</em>). These nodes in contrast have only <em>one</em> connection and that is to the central node, none among themselves.</p>
<p>Because of these restrictions, it is easy to see that if <span class="math inline">\(G = (V, E)\)</span> is a star graph of order <span class="math inline">\(n\)</span>, then we know that that graph size <span class="math inline">\(m = |E|\)</span> (the size of the edge set), has to be <span class="math inline">\(n-1\)</span>. So in the example shown in <a href="#fig-star">Figure&nbsp;<span>19.1</span></a>, <span class="math inline">\(n =7\)</span> and <span class="math inline">\(m = n-1 = 7-1=6\)</span>. Neat!</p>
</section>
<section id="degree-centrality" class="level2 page-columns page-full" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="degree-centrality"><span class="header-section-number">19.3</span> Degree Centrality</h2>
<p>The first way of defining centrality is simply as a measure of how many alters an ego is connected to. This simply takes a node’s degree as introduced in the lesson on graph theory, and begins to consider this measure as a reflection of importance of the node in the network. The logic is that those with more direct connections to others, compared to those with fewer, hold a more prominent place in the network.</p>
<p>Once we have constructed the <strong>adjacency matrix</strong> for the network (<strong>A</strong>), then degree centrality is easy to calculate. As <a href="#eq-degcen">Equation&nbsp;<span>19.1</span></a>) for a given node <em>i</em> the degree centrality is given by summing the entries of its corresponding row.</p>
<p><span id="eq-degcen"><span class="math display">\[
  C_i^{DEG} = \sum_{j= 1}^{n}a_{ij}
\tag{19.1}\]</span></span></p>
<p><a href="#eq-degcen">Equation&nbsp;<span>19.1</span></a> thus <em>ranks each node in the graph based on the number of other nodes that it is adjacent to</em>. Just like real life, some nodes will be popular (they will be adjacent to lots of other nodes), while others will be unpopular.</p>
<p>Although it might seem a simple task to just add up the number of connections of each node, that is essentially what the below mathematical equation is doing! Mathematical notation plays an important role in expressing network measures in succinct formats.</p>
<p>For instance, if we were to use <a href="#eq-degcen">Equation&nbsp;<span>19.1</span></a> to calculate the degree centrality of each node from the symmetric adjacency matrix corresponding to the graph shown in <a href="lesson-ties-and-graphs.html#fig-undirected">Figure&nbsp;<span>8.1</span></a>) then we would end up with the following degree centralities for each node:</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-degcen" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">I</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.1: Degree centralities of nodes in an undirected graph.</div></div>
</div>
</div>
<section id="how-to-read-equations-for-matrix-operations" class="level3" data-number="19.3.1">
<h3 data-number="19.3.1" class="anchored" data-anchor-id="how-to-read-equations-for-matrix-operations"><span class="header-section-number">19.3.1</span> How to Read Equations for Matrix Operations</h3>
<p>Before we continue, a note on something obvious. A lot of centrality measures are expressed as equations and these can be hard to interpret initially. Depending on your background in math, you may or may not already know how to interpret <a href="#eq-degcen">Equation&nbsp;<span>19.1</span></a>). Essentially, the number at the bottom of the sigma is where to start. The number at the top of the Sigma symbol (<span class="math inline">\(\Sigma\)</span>) is where to end. The equation to the left is the operation to be performed. Thus, one reads the <a href="#eq-degcen">Equation&nbsp;<span>19.1</span></a> as, starting at column <span class="math inline">\(j=1\)</span>, and ending at the last possible column <span class="math inline">\(n\)</span> (<span class="math inline">\(n\)</span> is simply the total number of rows in the matrix, <span class="math inline">\(n\)</span> means to go to the final value in the matrix), add up all possible values of the cells designated by the row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span> combination in matrix <strong>A</strong>. Thus, to calculate the degree centrality of each <span class="math inline">\(j = a, b, c\)</span> in the below matrix, each of the following calculations would be performed.</p>
<div id="tbl-simp" class="anchored">
<table class="table">
<caption>Table&nbsp;19.2: Simple matrix.</caption>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">a</th>
<th style="text-align: center;">b</th>
<th style="text-align: center;">c</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>a</strong></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>b</strong></td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>c</strong></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">-</td>
</tr>
</tbody>
</table>
</div>
<p><span class="math inline">\(C_D(a)=aa+ab+ac=1\)</span><br>
<span class="math inline">\(C_D(b)=ba+bb+bc=2\)</span><br>
<span class="math inline">\(C_D(c)=ca+cb+cb=1\)</span></p>
<p>In the same way if we had the formula:</p>
<p><span class="math display">\[
  C_D(j) = \sum_{i = 1}^{n}a_{ij}
\]</span></p>
<p>Then it would be telling us to sum values of each column <span class="math inline">\(j\)</span> <strong>down</strong> each row <span class="math inline">\(i\)</span>:</p>
<p><span class="math inline">\(C_D(a)=aa+ba+ca=1\)</span><br>
<span class="math inline">\(C_D(b)=ab+bb+cb=2\)</span><br>
<span class="math inline">\(C_D(c)=ac+bc+cc=1\)</span></p>
<p>The sigma notation is useful for summarizing this repetitive process in a simple, condensed form.</p>
</section>
</section>
<section id="indegree-and-outdegree-centrality" class="level2 page-columns page-full" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="indegree-and-outdegree-centrality"><span class="header-section-number">19.4</span> Indegree and Outdegree Centrality</h2>
<p>If we are talking about a <strong>directed graph</strong>, then there are two types of degree centralities that can be calculated. On the one hand, we may be interested in how central a node is in terms of <em>sociability</em> or <em>expansiveness</em> that is how many other nodes in the graph a given node <strong>sends</strong> links to. This is called the <strong>outdegree centrality</strong> of that node, written as <span class="math inline">\(C_i^{OUT}\)</span>. As with the undirected case, this is computed by summing across the rows of the <strong>asymmetric adjacency matrix</strong> corresponding to the directed graph in question, using <a href="#eq-degcen">Equation&nbsp;<span>19.1</span></a>:</p>
<p><span id="eq-outdegcen"><span class="math display">\[
  C_i^{OUT} = \sum_ja_{ij}
\tag{19.2}\]</span></span></p>
<p>However, in a directed graph, we may also be interested in how <em>popular</em> or <em>sought after</em> by others a given node is. That is, how many other actors send ties <em>to</em> that node. In which case we need to sum across the <strong>columns</strong> of the asymmetric adjacency matrix, and modify the formula as follows:</p>
<p><span id="eq-indegcen"><span class="math display">\[
  C_i^{IN} = \sum_ia_{ij}
\tag{19.3}\]</span></span></p>
<p>Note that in this version of the equation, we are summing over <em>j</em> (the columns) not over <em>i</em> (the rows) as given by subscript under the <span class="math inline">\(\sum\)</span> symbol.</p>
<p>For instance, if we were to use equations <a href="#eq-outdegcen">Equation&nbsp;<span>19.2</span></a> and <a href="#eq-outdegcen">Equation&nbsp;<span>19.2</span></a> to calculate the outdegree and indegree centrality of each node from the asymmetric adjacency matrix corresponding to the graph shown in <a href="lesson-ties-and-graphs.html#fig-directed">Figure&nbsp;<span>8.2</span></a>), then we would up with the following centralities for each node:</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-outindegcen" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Outdegre</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indegree</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.3: Out and Indegree centralities of nodes in a directed graph.</div></div>
</div>
</div>
<p>Just like the degree centrality for undirected graphs, the outdegree and indegree centralities rank each node in a directed graph. The first, outdegree centrality, ranks each node based on the number of other nodes that they are connected to. This is a kind of popularity based on <em>sociability</em>, or the tendency to seek out the company of others. The second, indegree centrality, ranks each node in the graph based on the number of other nodes that connect to that node. This is a kind of popularity based on on <em>being sought after</em> a kind of status.</p>
<section id="sec-normdeg" class="level3" data-number="19.4.1">
<h3 data-number="19.4.1" class="anchored" data-anchor-id="sec-normdeg"><span class="header-section-number">19.4.1</span> Normalized Degree Centrality</h3>
<p>When we compute the degree centrality of a node, are counting the number of other nodes that they are connected to. Obviously, the more nodes there are to connect to, the more opportunities there will be to reach a larger number. But what happens if we wanted to compare the degree centrality of nodes in two very different networks?</p>
<p>For instance, if your high-school has one thousand people and you have twenty friends, that’s very different from having twenty friends in a high-school of only one hundred people. It seems like the second person, with twenty friends (covering 20% of the population) in a high-school of one-hundred people is definitely more popular than the second person with twenty friends (covering 2% of the population), in a high school with one thousand people.</p>
<p>That’s why Freeman <span class="citation" data-cites="freeman79">Freeman (<a href="#ref-freeman79" role="doc-biblioref">1979</a>)</span> proposed <em>normalizing</em> the degree centrality of each node by the <em>maximum</em> possible it can take in a given network. As you may have guessed, the maximum degree in a network is <span class="math inline">\(N-1\)</span> the order of the graph minus one. Essentialy, everyone but you!</p>
<p>We can compute the normalized degree centrality using the following equation:</p>
<p><span id="eq-indegcen"><span class="math display">\[
  C_{i(norm)}^{DEG} = \frac{C_{i}^{DEG}}{N-1}
\tag{19.4}\]</span></span></p>
<p>Where we just divide the regular degree centrality computed using <a href="#eq-degcen">Equation&nbsp;<span>19.1</span></a> by the order of the graph minus one. This will be equal to <span class="math inline">\(1.0\)</span> if a person knows <em>everyone</em> and <span class="math inline">\(0\)</span> is a person knows <em>no one</em>. For all the other nodes it will be a number between zero and one.</p>
<p>Moreover, this measure is sensitive to the order of the graph. Thus, for a person with twenty friends in a high-school of a thousand people, the normalized degree centrality is equal to:</p>
<p><span id="eq-indegcen"><span class="math display">\[
  C_{i(norm)}^{DEG} = \frac{20}{1000-1}= 0.02
\tag{19.5}\]</span></span></p>
<p>But for the person with the same twenty friends in a high-school of one-hundred people, it is equal to:</p>
<p><span id="eq-indegcen"><span class="math display">\[
  C_{i(norm)}^{DEG} = \frac{20}{100-1}= 0.20
\tag{19.6}\]</span></span></p>
<p>Indicating that a person with the same number of friends in the smaller place is indeed more central!</p>
</section>
</section>
<section id="closeness-centrality" class="level2 page-columns page-full" data-number="19.5">
<h2 data-number="19.5" class="anchored" data-anchor-id="closeness-centrality"><span class="header-section-number">19.5</span> Closeness Centrality</h2>
<p>Sometimes it not important how many people you <em>directly</em> connected to. Instead, what is important is that you are <strong>indirectly connected</strong> to a lot of others. As we saw in the lesson on indirect connectivity, the best way to conceptualize indirect connectivity in social networks is via the idea of <strong>shortest paths</strong>. So if you can reach the most other people in the network via shortest paths with only a few hops, then you are better connected that someone who has to use longer paths to reach the same other people.</p>
<div class="cell" data-fig-cap-location="margin">
<div class="cell-output-display">
<div id="fig-clos" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lesson-centrality_files/figure-html/fig-clos-1.png" class="img-fluid figure-img" width="1152"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;19.2: An undirected graph showing the node with the maximum closeness centrality (in red).</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>This insight serves as an inspiration for a measure of centrality based on <strong>closeness</strong>. The closeness between two nodes is the <em>inverse</em> of the <strong>geodesic distance</strong> them <span class="citation" data-cites="bavelas50">(<a href="#ref-bavelas50" role="doc-biblioref">Bavelas 1950</a>)</span>. Recall that the geodesic distance is given by the <em>length of the shortest path linking two nodes in the graph</em>. The smallest the length of the shortest path separating two nodes in the graph, the closer the two nodes and vice versa.</p>
<p>Remember that for any number <span class="math inline">\(n\)</span>, the mathematical operation of <em>taking the inverse</em> simply means dividing one by that number. So, the inverse of <span class="math inline">\(n\)</span> is <span class="math inline">\(\frac{1}{n}\)</span>. This means that if <span class="math inline">\(d_{ij}\)</span> is the geodesic distance between nodes <em>i</em> and <em>j</em> in graph <span class="math inline">\(G\)</span>, then the closeness between two nodes is <span class="math inline">\(\frac{1}{d+_{ij}}\)</span>.</p>
<p>The information on the pairwise geodesic distances between every pair of nodes in a given graph is captured in the geodesic <strong>distance matrix</strong>, as discussed in <a href="lesson-special-matrices.html"><span>Chapter&nbsp;14</span></a>. For instance, take the graph shown in <a href="#fig-clos">Figure&nbsp;<span>19.2</span></a>. The distance matrix for this graph is shown in <a href="#tbl-dis">Table&nbsp;<span>19.4</span></a>.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-dis" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">L</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">J</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">K</th>
<th style="text-align: center;">I</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">M</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">L</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">J</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">N</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">D</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">C</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">K</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.4: Geodesic distance matrix for an undirected graph.</div></div>
</div>
</div>
<p>As shown in <a href="#tbl-dis">Table&nbsp;<span>19.4</span></a>, a node like <em>I</em>, who seems to be at the outskirts of the network, also shows up as having the largest geodesic distances from other nodes in the graph. Other nodes, like <em>E</em>, <em>G</em>, and <em>L</em> seem to be “closer” to others, in terms of having to traverse smaller geodesic distances to reach them.</p>
<p>That means that we can use the distance table to come up with a measure of centrality called <strong>closeness centrality</strong> for each node. We can do that by adding up the entries corresponding to each row in the distance matrix (<span class="math inline">\(\sum_j d_{ij}\)</span>), to get a summary the total pairwise distances separating the node corresponding to row <em>i</em> in the matrix from the other nodes listed in each column <em>j</em>.</p>
<p>Note that because closeness is better than “farness,” we would want the node with <em>highest closeness centrality</em> to be the one with the <em>smallest</em> sum of pairwise distances. This can be calculated using the following equation:</p>
<p><span id="eq-closcen"><span class="math display">\[
  C_i^{CLOS} = \frac{1}{\sum_jd_{ij}}
\tag{19.7}\]</span></span></p>
<p>In <a href="#eq-closcen">Equation&nbsp;<span>19.7</span></a>, the denominator is the sum across each column <em>j</em>, for each row <em>i</em> in <a href="#tbl-dis">Table&nbsp;<span>19.4</span></a> which corresponds to the distance between node <em>i</em> and each of the other nodes in the graph <em>j</em> (skipping the diagonal cell when <span class="math inline">\(i=j\)</span>, because the geodesic distance of node to itself is always zero!).</p>
<p>As noted, we take the mathematical inverse of this quantity, dividing one by the sum of the distances, so that way, the smallest number comes out on top and the bigger number comes out on the bottom (since, as we said, we want to measure <em>closeness</em> not “farness.”)</p>
<p>Let’s see how this work for the graph in <a href="#fig-clos">Figure&nbsp;<span>19.2</span></a>. First, we get the row sums of geodesic distances from <a href="#tbl-dis">Table&nbsp;<span>19.4</span></a>. These are shown in the first column of <a href="#tbl-clos">Table&nbsp;<span>19.5</span></a>, under the heading “Sum of Distances.” This seems to work; node <span class="math inline">\(E\)</span> has the smallest number here (<span class="math inline">\(\sum_j d_{Ej} = 22\)</span>) suggesting it can reach the most nodes via the shortest paths. Node <span class="math inline">\(I\)</span> has the largest number (<span class="math inline">\(\sum_j d_{Ij} = 35\)</span>) indicating it is the most isolated from the other nodes.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-clos" class="anchored page-columns page-full">

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> Sum of Distances (d) </th>
   <th style="text-align:center;"> Inverse (1/d) </th>
   <th style="text-align:center;"> Normalized (N-1/d) </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;font-weight: bold;"> E </td>
   <td style="text-align:center;font-weight: bold;"> 22 </td>
   <td style="text-align:center;font-weight: bold;"> 0.045 </td>
   <td style="text-align:center;font-weight: bold;"> 0.59 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> A </td>
   <td style="text-align:center;"> 25 </td>
   <td style="text-align:center;"> 0.040 </td>
   <td style="text-align:center;"> 0.52 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> M </td>
   <td style="text-align:center;"> 28 </td>
   <td style="text-align:center;"> 0.036 </td>
   <td style="text-align:center;"> 0.46 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> L </td>
   <td style="text-align:center;"> 23 </td>
   <td style="text-align:center;"> 0.043 </td>
   <td style="text-align:center;"> 0.57 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> B </td>
   <td style="text-align:center;"> 28 </td>
   <td style="text-align:center;"> 0.036 </td>
   <td style="text-align:center;"> 0.46 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> J </td>
   <td style="text-align:center;"> 23 </td>
   <td style="text-align:center;"> 0.043 </td>
   <td style="text-align:center;"> 0.57 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> G </td>
   <td style="text-align:center;"> 24 </td>
   <td style="text-align:center;"> 0.042 </td>
   <td style="text-align:center;"> 0.54 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> N </td>
   <td style="text-align:center;"> 24 </td>
   <td style="text-align:center;"> 0.042 </td>
   <td style="text-align:center;"> 0.54 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> F </td>
   <td style="text-align:center;"> 23 </td>
   <td style="text-align:center;"> 0.043 </td>
   <td style="text-align:center;"> 0.57 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> H </td>
   <td style="text-align:center;"> 24 </td>
   <td style="text-align:center;"> 0.042 </td>
   <td style="text-align:center;"> 0.54 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> D </td>
   <td style="text-align:center;"> 25 </td>
   <td style="text-align:center;"> 0.040 </td>
   <td style="text-align:center;"> 0.52 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> C </td>
   <td style="text-align:center;"> 26 </td>
   <td style="text-align:center;"> 0.038 </td>
   <td style="text-align:center;"> 0.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> K </td>
   <td style="text-align:center;"> 26 </td>
   <td style="text-align:center;"> 0.038 </td>
   <td style="text-align:center;"> 0.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> I </td>
   <td style="text-align:center;"> 35 </td>
   <td style="text-align:center;"> 0.029 </td>
   <td style="text-align:center;"> 0.37 </td>
  </tr>
</tbody>
</table>

<div class="quarto-table-caption margin-caption">Table&nbsp;19.5:  Sum of geodesic distances for each node in an undirected graph and its inverse. </div></div>
</div>
</div>
<p>But we want closeness, not farness, so the second column of <a href="#tbl-clos">Table&nbsp;<span>19.5</span></a> shows what happens when we divide one by the number in the second column. Now, node <span class="math inline">\(E\)</span> has the largest score <span class="math inline">\(CC^{CLOS}_E = 0.045\)</span> which is what we want.</p>
<p>However, because we are dividing one by a relatively large number, we end up with a bunch of small decimal numbers as centrality scores, and like it happened with degree, this number is sensitive to how big the network is (the larger the network, the more likely there is to be really long short paths). So <span class="citation" data-cites="freeman79">Freeman (<a href="#ref-freeman79" role="doc-biblioref">1979</a>)</span> proposes a <em>normalized</em> version of closeness that takes into account network size. It is a variation of <a href="#eq-closcen">Equation&nbsp;<span>19.7</span></a>:</p>
<p><span id="eq-closnorm"><span class="math display">\[
  C_i^{CLOS} = \frac{N-1}{\sum_jd_{ij}}
\tag{19.8}\]</span></span></p>
<p><a href="#eq-closnorm">Equation&nbsp;<span>19.8</span></a> is the same as <a href="#eq-closcen">Equation&nbsp;<span>19.7</span></a>, except that instead of dividing one by the sum of distances, we divide <span class="math inline">\(N-1\)</span> by the sum of distances, where <span class="math inline">\(N\)</span> is the order of the graph (the number of nodes). In this case, <span class="math inline">\(N=14\)</span>.</p>
<p>Normalizing the sum of distances shown in the second column of <a href="#tbl-clos">Table&nbsp;<span>19.5</span></a> according to <a href="#eq-closnorm">Equation&nbsp;<span>19.8</span></a>, gives us the centrality scores shown in the fourth column of the table, under the heading “Normalized.” These scores range from zero to one, with one being the maximum possible closeness centrality score for that graph.</p>
<p>The normalized closeness centrality scores listed in the fourth column of <a href="#tbl-clos">Table&nbsp;<span>19.5</span></a> agree with our informal impressions. Node <em>I</em> comes out at the bottom (<span class="math inline">\(CC_I^{CLOS} = 0.37\)</span>), showing it to be the one with the least closeness centrality, given the relatively large geodesic distances separating it from the other nodes in the graph. Node <em>E</em> (marked red in <a href="#fig-clos">Figure&nbsp;<span>19.2</span></a>) comes out on top (<span class="math inline">\(CC_E^{CLOS} = 0.59\)</span>), given its relative geodesic proximity to other nodes in the graph.</p>
<p>As we will see later, having closeness centrality information for nodes in a graph can be useful. For instance, if <a href="#fig-clos">Figure&nbsp;<span>19.2</span></a> was a social network, and we wanted to spread an innovation or a new product among the actors in the fastest amount of time, we would want to give it to node <em>E</em> first. Note however that if something <strong>bad</strong> (like a disease) was spreading across the network, then it would also be very bad if actor <em>E</em> got it first!<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</section>
<section id="houston-we-have-a-problem" class="level2 page-columns page-full" data-number="19.6">
<h2 data-number="19.6" class="anchored" data-anchor-id="houston-we-have-a-problem"><span class="header-section-number">19.6</span> Houston, We Have a Problem</h2>
<p>So far, so good. Closeness seems to be a great measure of node importance, giving us a sense of who can reach most others in a network in the most efficient way. However, what would happen if we tried to compute closeness centrality for a <strong>disconnected graph</strong> like the one shown in Figure <a href="lesson-indirect-connections.html#fig-connected1-2">Figure&nbsp;<span>7.2 (b)</span></a>? Well, the shortest paths distance matrix for that graph looks like the one in <a href="#tbl-dis2">Table&nbsp;<span>19.6</span></a>.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-dis2" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">I</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.6: Geodesic distance matrix for an undirected, disconnected graph.</div></div>
</div>
</div>
<p>Note that in <a href="#tbl-dis2">Table&nbsp;<span>19.6</span></a>, pairs of nodes that cannot <strong>reach</strong> one another in the disconnected graph, get a geodesic distance of “Inf” (infinity) in the respective cell of the geodesic distance matrix. This is a problem because when we compute the row sums of the geodesic distance matrix to try to calculate centrality according to <a href="#eq-closcen">Equation&nbsp;<span>19.7</span></a>, we get the “numbers” shown in <a href="#tbl-inf">Table&nbsp;<span>19.7</span></a>.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-inf" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">I</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
<td style="text-align: center;">Inf</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.7: Row sums of a geodesic distance matrix from a disconnected graph.</div></div>
</div>
</div>
<p>So that’s a bummer since all the “numbers” in <a href="#tbl-inf">Table&nbsp;<span>19.7</span></a>, are just infinity. Not to get too philosophical, but the problem is that when you add any number to “infinity,” the answer is, well, <em>infinity</em>.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> This means that closeness centrality is only defined for <strong>connected graphs</strong>. When it comes to disconnected graphs, we are out of luck.</p>
<p>Thankfully, there is a solution develoed by <span class="citation" data-cites="beauchamp65">Beauchamp (<a href="#ref-beauchamp65" role="doc-biblioref">1965</a>)</span>. It consists of a modification of <a href="#eq-closcen">Equation&nbsp;<span>19.7</span></a> called <strong>harmonic closeness centrality</strong>. The formula goes as follows:</p>
<p><span id="eq-harmcen"><span class="math display">\[
  C_i^{HARM} = \frac{1}{N-1}\sum_j\frac{1}{d_{ij}}
\tag{19.9}\]</span></span></p>
<p>Now, this might seem like we just re-arranged the stuff in <a href="#eq-closnorm">Equation&nbsp;<span>19.8</span></a>, and indeed that’s what we did! But the re-arrangement matters a lot, because it changes the <em>order</em> in which we do the various arithmetic operations <span class="citation" data-cites="boldi14">(<a href="#ref-boldi14" role="doc-biblioref">Boldi and Vigna 2014</a>)</span>.</p>
<p>So, in English, while <a href="#eq-closnorm">Equation&nbsp;<span>19.8</span></a> says “<em>first</em> sum the geodesic distances for each node (to get the denominator), and <em>then</em> divide <span class="math inline">\(N-1\)</span> by this sum,” <a href="#eq-harmcen">Equation&nbsp;<span>19.9</span></a> says “<em>first</em> divide one by the geodesic distance, and <em>then</em> sum the result of all these divisions, and <em>then</em> multiply this sum by one over <span class="math inline">\(N-1\)</span>.</p>
<p>Once again, the philosophy of mathematical infinity kicks in here, since the main difference is that one divided by infinity is actually a real number: <strong>zero</strong>.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p>So let’s check by taking every entry in <a href="#tbl-dis2">Table&nbsp;<span>19.6</span></a> and dividing one by the number in each cell (except for the diagonals, which we don’t care about). The results are shown in <a href="#tbl-dis3">Table&nbsp;<span>19.8</span></a>.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-dis3" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">I</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">G</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.8: Reciprocal of the geodesic distance matrix for an undirected, disconnected graph.</div></div>
</div>
</div>
<p>Beautiful! Now, instead of weird “Inf”s we have zeroes, which is great because we can add stuff to zero and get a real number back. We can then apply <a href="#eq-harmcen">Equation&nbsp;<span>19.9</span></a> to the numbers in <a href="#tbl-dis3">Table&nbsp;<span>19.8</span></a> (e.g., computing the sum of each row and then multiplying that by <span class="math inline">\(\frac{1}{N-1}\)</span>) to get the <strong>harmonic closeness centrality</strong> for each node in <a href="lesson-indirect-connections.html#fig-connected1-2">Figure&nbsp;<span>7.2 (b)</span></a>. These are shown in <a href="#tbl-clos2">Table&nbsp;<span>19.9</span></a>.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-clos2" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">I</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.44</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.44</td>
<td style="text-align: center;">0.38</td>
<td style="text-align: center;">0.38</td>
<td style="text-align: center;">0.38</td>
<td style="text-align: center;">0.38</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.9: Harmonic Closeness Centrality scores for nodes in a disconnected, undirected graph.</div></div>
</div>
</div>
<p>Great! Now we have a measure of closeness centrality we can apply to all kinds of graphs, whether they are <strong>connected</strong> or <strong>disconnected</strong>.</p>
</section>
<section id="betweenness-centrality" class="level2 page-columns page-full" data-number="19.7">
<h2 data-number="19.7" class="anchored" data-anchor-id="betweenness-centrality"><span class="header-section-number">19.7</span> Betweenness Centrality</h2>
<p>Recall that in our discussion of shortest paths between pair of nodes in the lesson on indirect connections, we noted the importance of the inner nodes that <em>intervene</em> or <em>mediate</em> between a node that wants to reach another one. Nodes that stand in these <strong>brokerage</strong> or <strong>gatekeeper</strong> slots in the network, occupy an important position <span class="citation" data-cites="marsden83">(<a href="#ref-marsden83" role="doc-biblioref">Marsden 1983</a>)</span>, and this is different from having a lot of contacts (like degree centrality), or being able to reach lots of other nodes by traversing relatively small distances (like closeness centrality). Instead, this is about being <em>in-between</em> the indirect communications of other nodes in graph. We can compute a centrality metric for each node called <strong>betweenness centrality</strong> that captures this idea <span class="citation" data-cites="freeman77">Freeman (<a href="#ref-freeman80" role="doc-biblioref">1980</a>)</span>.</p>
<div class="cell" data-fig-cap-location="margin">
<div class="cell-output-display">
<div id="fig-bet" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="lesson-centrality_files/figure-html/fig-bet-1.png" class="img-fluid figure-img" width="1152"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;19.3: An undirected graph showing the node with the maximum betweenness centrality (in red)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>For instance, let’s say you were actor <em>K</em> in the network shown in <a href="#fig-clos">Figure&nbsp;<span>19.2</span></a>, and you wanted to know who is the person that you depend on the most to communicate with actor <em>J</em>. Here dependence means that you are forced to “go through them” if <em>I</em> wanted to reach <em>N</em> via a shortest path. One way <em>K</em> could figure this out is by listing every shortest path having them as the <strong>origin node</strong> and having <em>N</em> as the <strong>destination node</strong>. After you have this list, you can see which of other other nodes shows up as an <strong>inner node</strong>—an intermediary or gatekeeper—in those paths the most times.</p>
<p>This shortest path list would look like this:</p>
<ol type="1">
<li><p><span class="math inline">\(\{KH, HF, FJ\}\)</span></p></li>
<li><p><span class="math inline">\(\{KD, DF, FJ\}\)</span></p></li>
<li><p><span class="math inline">\(\{KH, HN, NJ\}\)</span></p></li>
<li><p><span class="math inline">\(\{KA, AC, CJ\}\)</span></p></li>
<li><p><span class="math inline">\(\{KA, AE, EJ\}\)</span></p></li>
<li><p><span class="math inline">\(\{KH, HE, EJ\}\)</span></p></li>
</ol>
<p>There are six shortest paths of length three indirectly connecting actors <em>K</em> and <em>J</em> in <a href="#fig-clos">Figure&nbsp;<span>19.2</span></a>), with nodes <span class="math inline">\(\{A, C, D, E, F, H, N\}\)</span> showing up as an inner node in at least one of those paths. To see which other actor in the network is the most frequent intermediary between <em>J</em> and <em>K</em>, we can create a list with the number of times each of these nodes shows up as an intermediary in this shortest path list. This would look like this:</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-pairdep" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: center;">Node</th>
<th style="text-align: center;">Freq.</th>
<th style="text-align: center;">Prop.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">C</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.17</td>
</tr>
<tr class="odd">
<td style="text-align: center;">D</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.17</td>
</tr>
<tr class="even">
<td style="text-align: center;">E</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="odd">
<td style="text-align: center;">F</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.33</td>
</tr>
<tr class="even">
<td style="text-align: center;">H</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.50</td>
</tr>
<tr class="odd">
<td style="text-align: center;">N</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.17</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.10: Intermediaries between nodes J and K</div></div>
</div>
</div>
<p>So it looks like, looking at the second column of <a href="#tbl-pairdep">Table&nbsp;<span>19.10</span></a>, that <em>H</em> is the other actor that <em>J</em> depends on the most to reach <em>K</em>. A better way to quantify this, is to actually look at the <em>proportion</em> of paths linking <em>J</em> and <em>K</em> that a particular other node (like <em>H</em>) shows up in. Let’s call this <span class="math inline">\(p_{K(H)J}\)</span> which can be read as “the proportion of paths between <em>K</em> and <em>J</em> featuring <em>H</em> as an inner node.” This is shown in the third column of <a href="#tbl-pairdep">Table&nbsp;<span>19.10</span></a> We can write this in equation form like this:</p>
<p><span id="eq-pairdep"><span class="math display">\[
  p_{K(H)J} = \frac{g_{K(H)J}}{g_{KJ}} = \frac{3}{6} = 0.5
\tag{19.10}\]</span></span></p>
<p>In <a href="#eq-pairdep">Equation&nbsp;<span>19.10</span></a>, <span class="math inline">\(g_{K(H)J}\)</span> is the number of shortest paths linking <em>K</em> and <em>J</em> featuring <em>H</em> as an inner node, and <span class="math inline">\(g_{KJ}\)</span> is the total number of paths linking <em>K</em> and <em>J</em>. <span class="citation" data-cites="freeman80">Freeman (<a href="#ref-freeman80" role="doc-biblioref">1980</a>)</span> calls this measure the <strong>pair-dependency</strong> of actor <em>K</em> on actor <em>H</em> to reach a given node <em>J</em>. In this case, <span class="math inline">\(g_{K(H)J} = 3\)</span> and <span class="math inline">\(g_{KJ} = 6\)</span>, which means that actor <em>K</em> depends on actor <em>H</em> for fifty percent of their shortest path access to <em>J</em>. Making <em>H</em> the actor in the network <em>J</em> depends on the most to be able to reach <em>J</em>.</p>
<p>Generalizing this approach, we can do the same for each triplet of actors <em>i</em>, <em>j</em>, and <em>k</em> in the network. This is the basis for calculating betweenness centrality. That is, we can count the number of times <em>k</em> stands on the shortest path between two other actors <em>i</em> and <em>j</em>. We can all this number <span class="math inline">\(g_{i(k)j}\)</span>. We can then divide it by the total number of shortest paths linking actors <em>i</em> and <em>j</em> in the network, which we refer by <span class="math inline">\(g_{ij}\)</span>. Remember that two actors can be indirectly linked by <em>multiple shortest paths of the same length</em>, and that we can figure out how many short paths links pairs of actors in the network using the <strong>shortest paths matrix</strong>.</p>
<p>This ratio, written <span class="math inline">\(\frac{g_{i(k)j}}{g_{ij}}\)</span> then gives us the <em>proportion</em> of shortest paths in the network that have <em>i</em> and <em>j</em> as the end nodes and that feature <em>k</em> as an intermediary inner node. This can range from zero (no shortest paths between <em>i</em> and <em>j</em> feature node <em>k</em> as an intermediary) to one (all the shortest paths between <em>i</em> and <em>j</em> feature node <em>k</em> as an intermediary).</p>
<p>We can then use the following equation to compute the average of this proportion for each node <em>k</em> across each pair of actors in the network <em>i</em> and <em>j</em>:</p>
<p><span id="eq-betcen"><span class="math display">\[
  C_k^{BET} = \sum_i \sum_j \frac{g_{ikj}}{g_{ij}}
\tag{19.11}\]</span></span></p>
<p>Computing this quantity for the graph shown in <a href="#fig-bet">Figure&nbsp;<span>19.3</span></a>, yields the betweenness centrality scores shown in <a href="#tbl-bet">Table&nbsp;<span>19.11</span></a>.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-bet" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<colgroup>
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
<th style="text-align: center;">H</th>
<th style="text-align: center;">J</th>
<th style="text-align: center;">K</th>
<th style="text-align: center;">L</th>
<th style="text-align: center;">M</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">I</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">1.5</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6.8</td>
<td style="text-align: center;">11.4</td>
<td style="text-align: center;">9.3</td>
<td style="text-align: center;">6.3</td>
<td style="text-align: center;">4.8</td>
<td style="text-align: center;">10.8</td>
<td style="text-align: center;">3.7</td>
<td style="text-align: center;">16.4</td>
<td style="text-align: center;">2.8</td>
<td style="text-align: center;">5.3</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.11: Betweenness centrality scores.</div></div>
</div>
</div>
<p>The numbers in the Table can be readily interpreted as percentages. Thus, the fact that node <em>J</em> has a a betweenness centrality score of 10.8 tells us that they stand in about 11% of the shortest paths between pairs of nodes in the graph. Interestingly, as shown in <a href="#fig-bet">Figure&nbsp;<span>19.3</span></a>, the node that ends up with the highest betweenness score is <em>L</em> (<span class="math inline">\(C_L^{BET} = 16.4\)</span>), mostly due to the fact that node <em>I</em>, who has the lowest possible betweenness score of zero, depends on this node for access to every other actor in the network.</p>
<p>Note also that two <em>different</em> nodes end up being ranked first on closeness and betweenness centrality in the same network (compare the red nodes in <a href="#fig-clos">Figure&nbsp;<span>19.2</span></a> and <a href="#fig-bet">Figure&nbsp;<span>19.3</span></a>). This tells us that closeness and betweenness are analytically distinct measures of node position. One (closeness) gets at reachability, and the other (betweenness) gets at intermediation potential.</p>
</section>
<section id="the-big-three-centralities-in-the-star-graph" class="level2 page-columns page-full" data-number="19.8">
<h2 data-number="19.8" class="anchored" data-anchor-id="the-big-three-centralities-in-the-star-graph"><span class="header-section-number">19.8</span> The Big Three Centralities in the Star Graph</h2>
<p>Degree, Closeness, and Betweenness centralities have an interesting property that provides a conceptual connection between them <span class="citation" data-cites="freeman79">(<a href="#ref-freeman79" role="doc-biblioref">Freeman 1979</a>)</span>. Consider the star graph shown in <a href="#fig-star">Figure&nbsp;<span>19.1</span></a> with central node <em>A</em>. The degree, closeness, and betweenness centralities of the different nodes are shown in <a href="#tbl-startab">Table&nbsp;<span>19.12</span></a>).</p>
<p>Of course, by definition, we know beforehand that the central node in a star graph has to have the highest degree, since the degree of peripheral nodes is fixed to one and the degree of the central node is always <span class="math inline">\(n-1\)</span>, where <span class="math inline">\(n\)</span> is the graph order.</p>
<p>However, note also that the central node has to have the highest closeness, since it is directed by a path of length one (and edge) to every peripheral node, but each peripheral node can only reach other peripheral nodes in the graph by a path of length two. They are farther away from other nodes than the central node.</p>
<p>Finally, note that the central node in the star will also always have the highest betweenness because each of the paths of length two connecting every pair of peripheral nodes to one another <em>has</em> to include the central node. So it serves as the intermediary between any communication between peripheral nodes.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="tbl-startab" class="anchored page-columns page-full">
<table class="table table-sm table-striped">

<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">D</th>
<th style="text-align: center;">E</th>
<th style="text-align: center;">F</th>
<th style="text-align: center;">G</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Degree</td>
<td style="text-align: center;">6.0</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Closeness</td>
<td style="text-align: center;">8.2</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">4.5</td>
<td style="text-align: center;">4.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Betwenness</td>
<td style="text-align: center;">15.0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.0</td>
<td style="text-align: center;">0.0</td>
</tr>
</tbody>
</table>
<div class="quarto-table-caption margin-caption">Table&nbsp;19.12: Centralities in a star graph of order 7.</div></div>
</div>
</div>
<p>The mathematical sociologist <strong>Linton <span class="citation" data-cites="freeman79">Freeman (<a href="#ref-freeman79" role="doc-biblioref">1979</a>)</span></strong> thus thinks that the “big three” centrality measures are the big three precisely because they are maximized for the central node in a star graph.</p>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>

<!-- 




## K-Path Centrality

Sade (1989) introduced the idea of k-path centrality. Logically, nodes which are near lots of other nodes, even they are not directly connected, are more closely connected to the network than nodes which are loosely connected through other nodes. It is useful for researchers to be able to examine this easily if their research question calls for measuring this.

**K-Path Centrality**
$$ 
$$
C_k(j) = \sum_{j = 1}^{n}A^k_{ij}
$$
$$

To do this, we multiply the matrix by itself equivalent to the path length we are interested in solving for. For example, looking for a k-path of k=2 would find all nodes two steps away. To solve, one would simply square the matrix. If you remember from chapter 3, this is the same thing as a reachability matrix! Now, we've simply shifted our thinking about it, to realize that it is interpretable as a measure of centrality. With some manipulation of the graph, we can easily calculate how far away a given node is from alters to which they are not directly connected.  

Note that k-path centrality is actually a generalization of degree centrality. Note that this formula reduces to equivalence wtih degree centrality for k=1, as k=1 is simply the condition which asks if two nodes are adjacent or not. 


::: {.cell}
::: {.cell-output-display}
![](lesson-centrality_files/figure-html/kpathcent-1.png){width=672}
:::
:::

**Figure 4.1**

Figure 4.1 provides a simple example of how k-path centrality of two provides insights that degree centrality alone fails to provide. Nodes A and F both have a degree centrality of one. However, node F has a 2-path centrality of 3, while node A has a 2-path centrality of 2. We might then think of node F as better connected to the network than node A.   

-->


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-bavelas50" class="csl-entry" role="doc-biblioentry">
Bavelas, Alex. 1950. <span>“Communication Patterns in Task-Oriented Groups.”</span> <em>The Journal of the Acoustical Society of America</em> 22 (6): 725–30.
</div>
<div id="ref-beauchamp65" class="csl-entry" role="doc-biblioentry">
Beauchamp, Murray A. 1965. <span>“An Improved Index of Centrality.”</span> <em>Behavioral Science</em> 10 (2): 161–63.
</div>
<div id="ref-boldi14" class="csl-entry" role="doc-biblioentry">
Boldi, Paolo, and Sebastiano Vigna. 2014. <span>“Axioms for Centrality.”</span> <em>Internet Mathematics</em> 10 (3-4): 222–62.
</div>
<div id="ref-borgatti05" class="csl-entry" role="doc-biblioentry">
Borgatti, Stephen P. 2005. <span>“Centrality and Network Flow.”</span> <em>Social Networks</em> 27 (1): 55–71.
</div>
<div id="ref-borgatti_everett06" class="csl-entry" role="doc-biblioentry">
Borgatti, Stephen P, and Martin G Everett. 2006. <span>“A Graph-Theoretic Perspective on Centrality.”</span> <em>Social Networks</em> 28 (4): 466–84.
</div>
<div id="ref-freeman77" class="csl-entry" role="doc-biblioentry">
Freeman, Linton C. 1977. <span>“A Set of Measures of Centrality Based on Betweenness.”</span> <em>Sociometry</em> 40 (1): 35–41.
</div>
<div id="ref-freeman79" class="csl-entry" role="doc-biblioentry">
———. 1979. <span>“Centrality in Social Networks Conceptual Clarification.”</span> <em>Social Networks</em> 1 (3): 215–39.
</div>
<div id="ref-freeman80" class="csl-entry" role="doc-biblioentry">
———. 1980. <span>“The Gatekeeper, Pair-Dependency and Structural Centrality.”</span> <em>Quality and Quantity</em> 14 (4): 585–92.
</div>
<div id="ref-marsden83" class="csl-entry" role="doc-biblioentry">
Marsden, Peter V. 1983. <span>“Restricted Access in Networks and Models of Power.”</span> <em>American Journal of Sociology</em> 88 (4): 686–717.
</div>
<div id="ref-nieminen74" class="csl-entry" role="doc-biblioentry">
Nieminen, Juhani. 1974. <span>“On the Centrality in a Graph.”</span> <em>Scandinavian Journal of Psychology</em> 15 (1): 332–36.
</div>
<div id="ref-sabidussi66" class="csl-entry" role="doc-biblioentry">
Sabidussi, Gert. 1966. <span>“The Centrality Index of a Graph.”</span> <em>Psychometrika</em> 31 (4): 581–603.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Or trails, or walks.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Or trails, or walks.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>If you need a refresher on these graph theory concepts, see the lesson indirect connectivity in social networks.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>See the discussion <a href="http://www.analytictech.com/networks/centaids.htm">here</a>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>For more details, see <a href="https://byjus.com/maths/infinity/">https://byjus.com/maths/infinity/</a><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Once again, see <a href="https://byjus.com/maths/infinity/">https://byjus.com/maths/infinity/</a><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./lesson-affiliation-networks.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Affiliation Networks</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./lesson-status.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Status</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>